/* ============================================================
   SILICON RELICS — data file
   This is the ONLY file content sweeps need to touch.
   Sweep 1 (2026-07-17): all published GitHub repos.
   ============================================================ */

const SITE = {
  tagline: "A living codex of homebrew, reverse engineering and porting quests across retro consoles — from the famous to the forgotten. A human + LLM collaboration, named openly.",
  updated: "2026-07-17",
};

/* Rarity reflects how obscure / undocumented the platform is.
   common → well-trodden ground … legendary → almost nobody has walked here. */
const RARITIES = {
  common:    { label: "Common Relic" },
  uncommon:  { label: "Uncommon Relic" },
  rare:      { label: "Rare Relic" },
  epic:      { label: "Epic Relic" },
  legendary: { label: "Legendary Relic" },
};

const TYPES = {
  homebrew: "Homebrew",
  porting:  "Porting",
  re:       "Reverse Eng.",
  tooling:  "Tooling",
};

const STATUSES = {
  accepted:  { label: "Quest Accepted", cls: "st-accepted" },
  ongoing:   { label: "In Progress",    cls: "st-ongoing" },
  bossfight: { label: "Boss Fight",     cls: "st-bossfight" },
  completed: { label: "Quest Complete", cls: "st-completed" },
};

const BADGES = {
  "first-boot":     { icon: "🕯️", label: "First Boot",            desc: "The relic drew breath: first successful boot of custom code." },
  "real-hardware":  { icon: "⚙️", label: "Runs on Real Hardware", desc: "Verified on the physical machine, not just emulation." },
  "audio-unlocked": { icon: "🎵", label: "Audio Unlocked",         desc: "Sound is alive on the platform." },
  "disasm":         { icon: "📜", label: "Scrolls Deciphered",     desc: "Significant disassembly / reverse engineering milestone." },
  "toolchain":      { icon: "🔨", label: "Forge Built",            desc: "A working toolchain / build pipeline was forged." },
  "released":       { icon: "🏆", label: "Released",               desc: "Shipped as a finished, usable release." },
  "world-first":    { icon: "🌍", label: "World First",            desc: "A documented first — nobody had done this before." },
};

/* Console generation labels for the "By Generation" view.
   90+ are special timeless groups, rendered after the console generations:
   90 = the PC (any era), 99 = the Forge (tools). */
const GENERATIONS = {
  2: { num: "II",   era: "1976 – 1983" },
  3: { num: "III",  era: "1983 – 1987" },
  4: { num: "IV",   era: "1987 – 1993" },
  5: { num: "V",    era: "1993 – 1998" },
  6: { num: "VI",   era: "1998 – 2005" },
  7: { num: "VII",  era: "2005 – 2012" },
  8: { num: "VIII", era: "2012 – 2020" },
  90: { num: "PC", title: "The Home Turf", era: "IBM PC & compatibles, 1981 → today" },
  91: { num: "✦",  title: "The Wunderkammer", era: "machines from stranger timelines" },
  99: { num: "∞",  title: "The Timeless Forge", era: "tools that serve the relics" },
};

/* ---------- Platforms (the Relics) ---------- */

const PLATFORMS = [
  {
    id: "coleco",
    name: "ColecoVision",
    maker: "Coleco",
    year: 1982,
    gen: 2,
    rarity: "uncommon",
    blurb: "1982's arcade-at-home wonder: a TMS9918 VDP, a Z80, and 1 KB of RAM — until the Super Game Module bolts on and suddenly there's room to dream much bigger.",
  },
  {
    id: "7800",
    name: "Atari 7800",
    maker: "Atari",
    year: 1986,
    gen: 3,
    rarity: "rare",
    blurb: "Atari's what-if console: no tilemaps, no sprite limits — just MARIA and her display lists, a 6502 heart, and a POKEY on the cartridge when you need real music.",
  },
  {
    id: "gx4000",
    name: "Amstrad GX4000",
    maker: "Amstrad",
    year: 1990,
    gen: 4,
    rarity: "epic",
    blurb: "Amstrad's ninety-day disaster: a CPC Plus in console clothing — Z80, ASIC hardware sprites, a 4096-colour palette — sunk by its own launch catalogue in a single Christmas.",
  },
  {
    id: "vis",
    name: "Tandy / Memorex VIS",
    maker: "Tandy · Memorex",
    year: 1992,
    gen: 4,
    rarity: "legendary",
    blurb: "The Video Information System: a CD console running Microsoft Modular Windows 3.1 on a 12 MHz 80286, with OPL3 FM synthesis. So forgotten even its ghosts need directions — now it runs raycasters.",
  },
  {
    id: "hyperscan",
    name: "Mattel HyperScan",
    maker: "Mattel",
    year: 2006,
    gen: 7,
    rarity: "legendary",
    blurb: "RFID trading cards, an S+Core CPU with an unmaintained compiler, zero storage, no SDK, no scene, discontinued within a year. The deepest public documentation of this machine lives in these quests.",
  },
  {
    id: "pippin",
    name: "Bandai Pippin @WORLD",
    maker: "Apple · Bandai",
    year: 1996,
    gen: 5,
    rarity: "legendary",
    blurb: "A stripped-down Macintosh sold as a console — PowerPC 603, Mac OS 7.5 fork, a GeoPort modem as its only road to the Internet. Barely documented, barely emulated.",
  },
  {
    id: "playdia",
    name: "Bandai Playdia",
    maker: "Bandai",
    year: 1994,
    gen: 5,
    rarity: "legendary",
    blurb: "Bandai's Japan-only anime-FMV machine: an 8-bit NEC CPU, an infrared controller, 42 titles — and every pixel routed through one custom chip nobody ever documented, the Asahi Kasei AK8000. No BIOS handshake, no disc auth: it boots whatever CD-R you burn.",
  },
  {
    id: "lynx",
    name: "Atari Lynx",
    maker: "Atari · Epyx",
    year: 1989,
    gen: 4,
    rarity: "uncommon",
    blurb: "The first color handheld — Epyx-designed, Atari-sold: a 65C02 flanked by Suzy and Mikey, hardware sprite scaling in 1989, ambidextrous by design. Crushed in the market by a Game Boy it outclassed on paper.",
  },
  {
    id: "gamecom",
    name: "Tiger Game.com",
    maker: "Tiger Electronics",
    year: 1997,
    gen: 5,
    rarity: "epic",
    blurb: "Tiger's folly ahead of its time: the first touchscreen game console — stylus, 14.4k modem cartridge, Internet dreams — driven by a Sharp SM8521 and a ghosting monochrome LCD. Remembered as a punchline; it deserved better.",
  },
  {
    id: "ngpc",
    name: "Neo Geo Pocket Color",
    maker: "SNK",
    year: 1999,
    gen: 5,
    rarity: "rare",
    blurb: "SNK's fierce 16-bit handheld (TLCS-900/H), with a proprietary Toshiba toolchain held together by decades-old links — and a link cable no emulator had ever spoken, on either side.",
  },
  {
    id: "wsc",
    name: "WonderSwan Color",
    maker: "Bandai",
    year: 2000,
    gen: 6,
    rarity: "rare",
    blurb: "Gunpei Yokoi's final console design: a Japan-only handheld with an x86-compatible V30MZ heart, a screen meant to be played horizontal or rotated vertical, and 20 hours on a single AA battery. Bandai's third relic in this codex.",
  },
  {
    id: "loopy",
    name: "Casio Loopy",
    maker: "Casio",
    year: 1995,
    gen: 5,
    rarity: "legendary",
    blurb: "Casio's 1995 machine for an audience nobody else was courting: an SH-1 console whose defining organ is a built-in thermal colour printer for making stickers — the only game console ever built to print. A NEC µPD937 chip sings the music. Japan-only, barely a dozen games, and a scene you can count on one hand.",
  },
  {
    id: "jaguar",
    name: "Atari Jaguar",
    maker: "Atari",
    year: 1993,
    gen: 5,
    rarity: "epic",
    blurb: "Atari's last stand: 'do the math', five processors that barely speak to each other, and a 68000 that was only ever meant to be the janitor — yet ends up doing most of the work.",
  },
  {
    id: "3do",
    name: "Panasonic 3DO",
    maker: "The 3DO Company · Panasonic",
    year: 1993,
    gen: 5,
    rarity: "epic",
    blurb: "The ambitious 1993 CD console of coded CELs, 32-colour PLUTs and no float runtime. A small modern devkit keeps the forge lit.",
  },
  {
    id: "32x",
    name: "Sega 32X",
    maker: "Sega",
    year: 1994,
    gen: 5,
    rarity: "rare",
    blurb: "Sega's ill-fated mushroom: two SH-2s bolted on top of a Genesis that still has its 68000 and Z80 underneath. Four CPUs, 4 MB of cart, and a short, angry life — all four processors get put to work here.",
  },
  {
    id: "saturn",
    name: "Sega Saturn",
    maker: "Sega",
    year: 1994,
    gen: 5,
    rarity: "uncommon",
    blurb: "Sega's baroque, misunderstood machine: two SH-2s, a VDP1 that draws quads instead of triangles, and a VDP2 that paints whole tile planes for free. A console with a reputation for fighting its own developers — and rewarding the ones who make peace with it.",
  },
  {
    id: "ps1",
    name: "Sony PlayStation",
    maker: "Sony",
    year: 1994,
    gen: 5,
    rarity: "common",
    blurb: "The grey box that redefined everything — and the best-charted territory in all of romhacking. For a kid who only had a PC, this was the stuff of playground legend.",
  },
  {
    id: "ps2",
    name: "PlayStation 2",
    maker: "Sony",
    year: 2000,
    gen: 6,
    rarity: "common",
    blurb: "The best-selling console ever made, and one of the most open homebrew targets of its era: the Emotion Engine and its twin vector units, a Graphics Synthesizer fed by hand-written VU1 microcode, audsrv streaming and gsKit. Common as relics go — but bending it to your will, one VU1 trap at a time, is anything but.",
  },
  {
    id: "n64",
    name: "Nintendo 64",
    maker: "Nintendo",
    year: 1996,
    gen: 5,
    rarity: "uncommon",
    blurb: "93.75 MHz of big-endian MIPS, 8 KB of data cache, high-latency RDRAM — and libdragon, the open-source toolchain that made its homebrew scene bloom without a single leaked SDK.",
  },
  {
    id: "dreamcast",
    name: "Sega Dreamcast",
    maker: "Sega",
    year: 1998,
    gen: 6,
    rarity: "uncommon",
    blurb: "Sega's swan song and homebrew's favourite harbour — KallistiOS territory, VMU saves, and an SH4 that rewards careful code.",
  },
  {
    id: "wiiu",
    name: "Nintendo Wii U",
    maker: "Nintendo",
    year: 2012,
    gen: 8,
    rarity: "uncommon",
    blurb: "The dual-screen underdog: big-endian PowerPC, a GamePad with a touch panel, and a homebrew scene that never gave up on it.",
  },
  {
    id: "snes",
    name: "Super Nintendo",
    maker: "Nintendo",
    year: 1990,
    gen: 4,
    rarity: "common",
    blurb: "The 16-bit king — common as relics go, but its Japanese text engines and sound drivers still guard secrets worth deciphering.",
  },
  {
    id: "cdi",
    name: "Philips CD-i",
    maker: "Philips",
    year: 1991,
    gen: 4,
    rarity: "epic",
    blurb: "Philips' interactive television that wasn't: a 68070 running OS-9's CDRTOS — no bare-metal soul here, but a real-time OS demanding properly-formed modules. Remembered for all the wrong games.",
  },
  {
    id: "cd32",
    name: "Amiga CD32",
    maker: "Commodore",
    year: 1993,
    gen: 5,
    rarity: "rare",
    blurb: "Commodore's last gamble: an Amiga 1200 heart in a CD console, 2 MB of chip RAM total, and the Akiko chip doing chunky-to-planar. Every kilobyte is negotiated.",
  },
  {
    id: "ds",
    name: "Nintendo DS",
    maker: "Nintendo",
    year: 2004,
    gen: 7,
    rarity: "common",
    blurb: "Two screens, two ARM CPUs, 4 MB of RAM and a touch panel begging to become a HUD. One of homebrew's best-loved homes.",
  },
  {
    id: "gba",
    name: "Game Boy Advance",
    maker: "Nintendo",
    year: 2001,
    gen: 6,
    rarity: "common",
    blurb: "A 16.78 MHz ARM7TDMI with 256 KB of work RAM — the pocket console that keeps saying yes to things it really shouldn't be able to run.",
  },
  {
    id: "pc",
    name: "The PC",
    maker: "IBM PC & compatibles",
    year: "1981 → today",
    gen: 90,
    rarity: "common",
    blurb: "Not obscure hardware — the childhood machine itself. Here the relics are the games: late-90s engines with debug symbols left inside, ciphers to crack, and party systems waiting to become something more.",
  },
  {
    id: "smaky",
    name: "Smaky 100",
    maker: "Epsitec · Lausanne",
    year: 1984,
    gen: 91,
    rarity: "legendary",
    blurb: "The Swiss school computer: a 68000 with green-phosphor 640×400, multitasking PSos in 1983, roughly 1,500 units ever built — for classrooms of French-speaking Switzerland. Yes, really.",
  },
  {
    id: "forge",
    name: "The Chip Forge",
    maker: "Browser-based · no install",
    year: 2026,
    gen: 99,
    rarity: "common",
    blurb: "Not a console: the workbench. Tools forged in the browser to serve the other relics — and the musicians who write for them.",
  },
];

/* ---------- Projects (the Quests) ---------- */

const PROJECTS = [

  /* ---- ColecoVision ---- */
  {
    id: "coleco-ff1",
    title: "Final Fantasy — ColecoVision",
    platform: "coleco",
    type: "porting",
    status: "ongoing",
    progress: 45,
    summary: "The 1987 NES RPG on 1982 hardware — a port nobody has ever attempted. Super Game Module and MegaCart banking make it possible; the TMS9918's color limits are beaten with per-row dominant colors plus sprite accent overlays, reaching visually NES-parity battle characters. All 24 songs extracted byte-exact from the disassembly onto the AY-3-8910. The twist versus the 7800 sibling: this port deliberately fixes Square's spell bugs — while preserving beloved quirks like the Finger Point peninsula, byte-exact. Overworld, Coneria and battle already loop under multi-bank.",
    milestones: [
      { label: "Toolchain + SGM bring-up — FF1 Fighter walks on Coleco", done: true },
      { label: "Overworld at 60 Hz with discrete tile movement", done: true },
      { label: "Audio: AY-3-8910 validated, 24 songs byte-exact", done: true },
      { label: "Battle screen at visual NES-parity (per-row colors + OAM accents)", done: true },
      { label: "MegaCart multi-bank architecture, OW+town+battle loop", done: true },
      { label: "Full battle engine with intent-fixed spells; 3 banking bugs open", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Atari 7800 ---- */
  {
    id: "7800-ff1",
    title: "Final Fantasy — Atari 7800",
    platform: "7800",
    type: "porting",
    status: "ongoing",
    progress: 50,
    summary: "The 1987 NES original rebuilt on Atari's forgotten console, working straight from the FF1 disassembly with a strict NES-parity policy — Square's original bugs cataloged, and fixable by choice. MARIA display lists replace the NES tilemaps, the toroidal overworld smooth-scrolls, Coneria has its real NPC dialogs and shops, and 4-character battles run with authentic stats, magic and enemy data — up to a playable Garland fight with his true sprite. The soundtrack pipeline runs through ChipRoll to POKEY: the Forge serving the quest. Target: a combat demo to the Pravoka bridge, on real hardware via modern flash carts.",
    milestones: [
      { label: "MARIA rendering foundation: display lists, metatiles, smooth scroll", done: true },
      { label: "Toroidal overworld with tile-locked movement and player sprite", done: true },
      { label: "Coneria: town maps, disasm-faithful NPC dialogs, shop data", done: true },
      { label: "Battle engine: 4-character rounds, magic, items, party targeting", done: true },
      { label: "Garland fight playable — real stats, real sprite", done: true },
      { label: "Demo-with-combat to the Pravoka bridge · full POKEY soundtrack", done: false },
    ],
    badges: ["toolchain", "first-boot", "disasm", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Amstrad GX4000 ---- */
  {
    id: "gx4000-jetpack",
    title: "Jetpack — Amstrad GX4000",
    platform: "gx4000",
    type: "porting",
    status: "ongoing",
    progress: 30,
    summary: "Adam Pedersen's 1993 DOS classic rebuilt for Amstrad's most famous flop. No source code exists: the 234 tiles and all 100 levels were extracted from the original data files, and the physics rebuilt TAS-faithful from the speedrun community's frame-perfect specs — subpixel movement, jetpack thrust, ladders, and the phaser that digs through the level grid. Sprites stored right-facing only, mirrored by the ASIC. A twin quest on the Atari 7800 is planned. And one rule above all: nothing ships until the original author says yes — the plan is a working prototype first, then a letter to Pedersen asking for his blessing.",
    milestones: [
      { label: "Asset pipeline: 234 tiles + 100 levels reconstructed from DAT files", done: true },
      { label: "CPCtelera toolchain — cart boots in MAME", done: true },
      { label: "Jetman runtime: TAS-faithful subpixel physics, jetpack, phaser", done: true },
      { label: "Full collisions, enemies, complete level loop", done: false },
      { label: "GX4000 deploy: true 12-bit palette on the ASIC", done: false },
      { label: "The author's blessing — then, maybe, the world", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Tandy VIS ---- */
  {
    id: "vis-wolf3d",
    title: "Wolfenstein 3D on the VIS",
    platform: "vis",
    type: "porting",
    status: "ongoing",
    progress: 85,
    summary: "A from-scratch Wolfenstein 3D port running natively as a Win16 app on the VIS: textured raycaster, enemy AI, combat, pickups — and a full 3-channel audio stack (FM music, AdLib SFX, digitized voices via raw DMA on the VIS DAC). 14–18 fps on a 12 MHz 286, and genuinely playable.",
    milestones: [
      { label: "Win16 toolchain + bootable VIS CD forged", done: true },
      { label: "Textured raycaster with doors, sprites and HUD", done: true },
      { label: "Enemy AI, hitscan combat, pickups, ammo economy", done: true },
      { label: "Full audio: IMF music + AdLib SFX + DAC digitized voices", done: true },
      { label: "Full-episode polish and stereo pan", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: ["https://raw.githubusercontent.com/vs-sr-dev/vis-wolf3d/main/wolfvis_demo.gif"],
    repo: "https://github.com/vs-sr-dev/vis-wolf3d",
  },
  {
    id: "vis-synth",
    title: "VIS Synth — an OPL3 instrument",
    platform: "vis",
    type: "homebrew",
    status: "completed",
    progress: 100,
    summary: "The VIS as a musical instrument: an 8-voice OPL3 polyphonic synth played on the hand controller, an SMF MIDI file player, and live MIDI from a real hardware keyboard via a custom MAME ISA-bridge card. All three modes verified — by a musician.",
    milestones: [
      { label: "Hand-controller polyphonic instrument (v0)", done: true },
      { label: "SMF MIDI file player with PIT-µs scheduler (v2)", done: true },
      { label: "Live MIDI from host hardware via custom MAME bridge (v3)", done: true },
    ],
    badges: ["audio-unlocked", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/vis-synth",
  },
  {
    id: "vis-fileviewer",
    title: "VIS File Viewer",
    platform: "vis",
    type: "homebrew",
    status: "completed",
    progress: 100,
    summary: "A media browser the VIS never shipped with: photos, WAV/MIDI audio and Autodesk FLC video played the native Modular Windows way — including a from-scratch FLC player with direct video-RAM writes, because that's how VIS video actually worked (spoiler: it was never AVI).",
    milestones: [
      { label: "Hand-controller file browser as CD shell", done: true },
      { label: "BMP photos + WAV/MIDI via native MCI", done: true },
      { label: "From-scratch FLC video player via DISPDIB DVA", done: true },
    ],
    badges: ["first-boot", "audio-unlocked"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/vis-fileviewer",
  },

  {
    id: "vis-dangerous-creatures",
    title: "Dangerous Creatures — Tandy VIS",
    platform: "vis",
    type: "porting",
    status: "ongoing",
    progress: 45,
    summary: "Microsoft's 1994 multimedia encyclopedia rebuilt as a native VIS title — arguably the software this edutainment console was born for and never received. The navigation database behind EXPLORE.EXE was fully reverse-engineered: 66 animals, 1,064 topics, all 719 referenced assets accounted for. The Lion vertical slice runs validated on the emulated VIS: legible hi-res 16-color pages, instant XOR hotspot cycling, popups with voiceover narration, and video playback — silent by hardware design, since the VIS's direct-video path mutes MCI audio; a PIT-paced direct-DAC path is the planned cure, borrowed from the Wolfenstein quest next door.",
    milestones: [
      { label: "MSDANGER.THE database cracked: 66 animals, 1,064 topics mapped", done: true },
      { label: "Asset pipeline: 719/719 referenced assets resolved and converted", done: true },
      { label: "Lion slice validated: hi-res pages, hotspots, voiceover popups, video", done: true },
      { label: "Synced video + audio via direct DAC in the PIT loop", done: false },
      { label: "Scale to the 25-animal subset on a single CD", done: false },
    ],
    badges: ["disasm", "toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  {
    id: "vis-ff1",
    title: "Final Fantasy — Tandy VIS",
    platform: "vis",
    type: "porting",
    status: "ongoing",
    progress: 40,
    summary: "The fourth runner in the FF1 sibling race — and the only one whose hardware can keep the logic 1:1 from the disassembly, no NES-style compromises. The discoveries stack up: a 320×240 CRTC mode with NES-equal height, hardware scroll via CRTC start-address panning, and the crown jewel — FF1's own sound engine ported to drive the OPL3 directly with byte-exact score data, after MCI's stuck notes were exhaustively ruled out. The whole opening flow — intro legend, title screen, party creation with six-letter names, and the full 256×256 overworld with a class-dynamic hero sprite — is stitched into a single EXE, verified on MAME with the Prelude looping cleanly.",
    milestones: [
      { label: "320×240 engine base + faithful intro, title, class and name screens", done: true },
      { label: "FF1's native sound engine on OPL3 — Prelude clean and looping", done: true },
      { label: "Full 256×256 overworld, smooth scroll, class-dynamic mapman", done: true },
      { label: "Opening flow stitched into one EXE, verified with music", done: true },
      { label: "Walkability, towns, password save, battles — the RPG itself", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked", "disasm"],
    screenshots: [],
    repo: null,
  },

  /* ---- Mattel HyperScan ---- */
  {
    id: "hyperscan-homebrew",
    title: "HyperScan: Charting the Uncharted",
    platform: "hyperscan",
    type: "re",
    status: "ongoing",
    progress: 85,
    summary: "The deepest public documentation of the HyperScan: 16+ reproducible bugs in the unmaintained score-elf GCC backend with verified workarounds, PPU register maps pushed all the way to dual-layer parallax blending and a three-phase 3D stress test, and a from-scratch RFID/NFC bit-banging driver — including hand-built 120-byte test cards proving the retail discs already hold all the card data. Crowning it: the first HyperScan audio ever emulated — a full SPU device written for MAME, down to discovering the DAC's true 54 MHz clock — A/B-matched against a real-hardware capture, then grown into a complete working audio stack with ADPCM and fixed-point resampling.",
    milestones: [
      { label: "16+ GCC score-elf compiler bugs root-caused", done: true },
      { label: "PPU register map + I²C controller driver", done: true },
      { label: "Stress tests: dual-layer parallax blending + 3-phase 3D demo", done: true },
      { label: "From-scratch RFID/NFC card driver; forged test cards decoded", done: true },
      { label: "First emulated HyperScan audio → full SPU stack in MAME", done: true },
      { label: "Further pipeline branches", done: false },
    ],
    badges: ["world-first", "disasm", "toolchain", "audio-unlocked", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/hyperscan-homebrew",
    links: [
      { label: "▶ First emulated HyperScan audio", url: "https://www.youtube.com/watch?v=1vh_27eTpfc" },
    ],
  },

  /* ---- Bandai Pippin ---- */
  {
    id: "pippin-homebrew",
    title: "Pippin Online — Networking the @WORLD",
    platform: "pippin",
    type: "re",
    status: "completed",
    progress: 100,
    summary: "The emulated Pippin brought onto the real Internet for the first time: DingusPPC serial/DBDMA fixes (upstreamable), a virtual modem + PPP host stack, Netscape 1.1N loading a live web page — plus a homebrew thin-client browser, and an honest falsification of the image-loading mystery.",
    milestones: [
      { label: "DingusPPC serial/DBDMA fixes (upstreamable)", done: true },
      { label: "Virtual Hayes modem + PPP/NAT host chain", done: true },
      { label: "Netscape loads a live web page from the real Internet", done: true },
      { label: "Thin-client homebrew browser architecture (PPF format)", done: true },
    ],
    badges: ["world-first", "disasm", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/pippin-homebrew",
  },

  {
    id: "pippin-dangerous-creatures",
    title: "Dangerous Creatures — Bandai Pippin",
    platform: "pippin",
    type: "porting",
    status: "ongoing",
    progress: 40,
    summary: "Microsoft's 1994 multimedia encyclopedia, take two — the sibling of the VIS quest, and an even stranger transplant: a Windows x86 title reborn on Apple and Bandai's PowerPC console. The original engine can't be ported, so the road is asset extraction plus a from-scratch C viewer (Retro68), grown out of the thin-client browser shell from the Pippin networking quest next door. The Lion vertical slice runs verified on the emulated Pippin: main page pixel-perfect on the first attempt (SZDD decompression → RGB555 → GWorld), clickable hotspots with five popups and the factbox, clean ADPCM voiceover narration — and the 'Fixing dinner' film playing with perfect sound, no codec on the console: Indeo 3.2 is pre-decoded offline into a raw frame stream the Pippin merely blits. Two memory walls fell along the way to a custom paged data-file format. What remains: taming video sync against an emulator clock that runs fast, scaling to all 66 animals via the navigation database cracked in the VIS sibling quest, and a bring-your-own-assets release.",
    milestones: [
      { label: "Recon: 3,346 bitmaps, 2,183 ADPCM WAVs, 109 Indeo AVIs — all extractable", done: true },
      { label: "Lion main page pixel-perfect on the Pippin, first attempt", done: true },
      { label: "Full Lion navigation: hotspots, 5 popups, factbox — memory walls beaten", done: true },
      { label: "Audio end-to-end: ADPCM narration clean through the Sound Manager", done: true },
      { label: "Video: Indeo film plays with perfect audio via codec-free frame streaming", done: true },
      { label: "Video sync, 66-animal scaling (VIS database crack), BYOA release", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Bandai Playdia ---- */
  {
    id: "playdia-ak8000",
    title: "The AK8000 Siege — Bandai Playdia",
    platform: "playdia",
    type: "re",
    status: "bossfight",
    progress: 50,
    summary: "The codex's purest siege: every chip in the Playdia is documented except one — the Asahi Kasei AK8000, the custom decoder every frame of video must pass through, with zero public documentation and zero emulation. Thirty-five sessions have taken its outer walls apart layer by layer: the disc anatomy fell first (a CD-XA multiplex hiding ~7 hours of ADPCM audio across seven retail titles, extracted with a from-scratch decoder where every ripping tool silently fails); then the paper trail — a cluster of December-1992 Asahi Chemical patents that turned out to describe the chip's own design; then the entropy layer itself, a variable-length code table solved to a perfect Kraft sum that parses 100% of every bitstream tested. What remains is the innermost keep: the mapping from parsed symbols to pixels, proven unrecoverable from desk-side statistics alone — locked in mask ROM and silicon. The next weapon has a name: hardware. And should the wall ever fall, what rises on the Playdia afterwards is a tale for another day.",
    milestones: [
      { label: "Disc anatomy mapped: CD-XA multiplex, AJS container, boot-from-disc model", done: true },
      { label: "~7 h of XA ADPCM audio decoded from scratch across 7 retail titles", done: true },
      { label: "1992 Asahi Chemical patent cluster identified as the AK8000's design", done: true },
      { label: "Entropy layer cracked: full VLC table, Kraft = 1.0, 100% parse cross-title", done: true },
      { label: "4×4 block structure + hardcoded quant table + rate-control semantics", done: true },
      { label: "BOSS: symbols → pixels. Geometry lives in the silicon; hardware trace next", done: false },
    ],
    badges: ["disasm", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Neo Geo Pocket Color ---- */
  {
    id: "ngpc-homebrew-notes",
    title: "NGPC ↔ Dreamcast Link Bridge",
    platform: "ngpc",
    type: "re",
    status: "ongoing",
    progress: 80,
    summary: "The NGPC link cable saw retail use in 1999 but had never been emulated on either side — until this three-ring bridge grew it back to life: an HLE loopback inside the NGPC emulator, then TCP between two NGPC instances, then the full span to a Dreamcast running in Flycast. Both a homebrew payload and retail software cross the gap, verified on video. Underneath sits real reverse engineering: the retail link protocol taken apart to a byte-perfect, deterministic end-to-end handshake — FF-delimited frames and a cable-probe sync header — plus genuine fixes to the beetle-ngp emulator itself, where a destructive packet-peek bug was corrected and a RAM comms side-channel gated so retail ROMs run clean by default. All of it riding on a rescued, fully-documented cc900 toolchain that had rotted behind dead links.",
    milestones: [
      { label: "cc900 toolchain rescued and documented (dead-link-proof)", done: true },
      { label: "Three-ring bridge: HLE loopback → TCP NGPC↔NGPC → Dreamcast via Flycast", done: true },
      { label: "Retail link protocol reverse-engineered — byte-perfect, deterministic E2E", done: true },
      { label: "beetle-ngp emulator fixes: peek-bug corrected, clean retail passthrough", done: true },
      { label: "Verified on video with both homebrew and retail software", done: true },
      { label: "Further pipeline branches", done: false },
    ],
    badges: ["world-first", "disasm", "toolchain", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/ngpc-homebrew-notes",
    links: [
      { label: "▶ First working bridge (homebrew)", url: "https://www.youtube.com/watch?v=x2IV3T3Z0oM" },
      { label: "▶ Retail-software bridge test", url: "https://www.youtube.com/watch?v=mmxnnkZzu-s" },
    ],
  },

  /* ---- Tiger Game.com ---- */
  {
    id: "gamecom-bringup",
    title: "Game.com Homebrew Bring-Up",
    platform: "gamecom",
    type: "homebrew",
    status: "ongoing",
    progress: 35,
    summary: "Tiger's mocked touchscreen handheld gets the modern toolchain it never had: with Sharp's DOS-era SDK lost to time, a from-scratch Python assembler for the SM8521 was built by inverting MAME's disassembler opcode table — flanked by a matching disassembler and a round-trip verifier to keep it honest. The BIOS turned out never to auto-launch cartridges: the launch protocol was reverse-engineered down to a BIOS vtable holding the cart-entry RAM pointer, then validated end-to-end. From there the climb: first pixel, a first interactive cart (D-pad pixel mover with erase-draw double buffering), the HALT-gated graphics-DMA protocol with its palette-forced fill trick, and readable text on screen via a VRAM-native 2bpp font atlas encoded offline in Python. Next up: the stylus — a 13×10 discrete touch grid, protocol already documented from static analysis. Where those gestures lead is a tale for another day.",
    milestones: [
      { label: "Custom SM8521 assembler + disassembler + round-trip verifier", done: true },
      { label: "BIOS cart-launch protocol cracked (vtable cart-entry pointer)", done: true },
      { label: "First pixel, then first interactive cart: D-pad + double buffering", done: true },
      { label: "Graphics DMA protocol + sprite primitives + include library", done: true },
      { label: "Readable text: VRAM-native 2bpp font atlas pipeline", done: true },
      { label: "Stylus input (13×10 grid, protocol documented) — toward a real app", done: false },
    ],
    badges: ["toolchain", "disasm", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Atari Lynx ---- */
  {
    id: "lynx-bringup",
    title: "Lynx Homebrew Bring-Up",
    platform: "lynx",
    type: "homebrew",
    status: "accepted",
    progress: 10,
    summary: "The quest is young, but the road is open: the cc65 toolchain proven end-to-end on Atari's ambidextrous pioneer, with a graphics hello world running under the Handy emulator and a reproducible Makefile pipeline standing ready. The classic first-timer traps are already documented for posterity — starting with the discovery that conio.h silently does nothing here: the Lynx speaks only TGI. Next on the horizon: sprites, the thing Suzy was born to scale.",
    milestones: [
      { label: "cc65 toolchain proven: TGI hello world runs under Handy", done: true },
      { label: "Reproducible build: Makefile, project layout, gotchas documented", done: true },
      { label: "Sprites and scaling — what this hardware was made for", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- WonderSwan Color ---- */
  {
    id: "wsc-bringup",
    title: "WonderSwan Color Homebrew Bring-Up",
    platform: "wsc",
    type: "homebrew",
    status: "accepted",
    progress: 10,
    summary: "Yokoi's swan gets its bring-up — the hard-won way: the modern Wonderful Toolchain (GCC targeting the V30MZ) fought back with five distinct traps before first light, from a package manager that self-upgrades mid-sync and exits without installing, through deprecated-header renames and a C-preprocessor stringification snare, to a build cache that ignores Makefile edits. All five documented and beaten. The reward on the other side: a hello world glowing in Mesen 2 — rendered vertical, of course, the way this rotating handheld always wanted to be held. Hardware header authored before the first line of C, as tradition demands.",
    milestones: [
      { label: "Wonderful Toolchain installed and proven — five build traps beaten", done: true },
      { label: "Hardware header + vertical hello world, first pixel in Mesen 2", done: true },
      { label: "Beyond hello: graphics, input, the real climb", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Casio Loopy ---- */
  {
    id: "loopy-homebrew",
    title: "The Printing Console — Casio Loopy",
    platform: "loopy",
    type: "homebrew",
    status: "ongoing",
    progress: 55,
    summary: "The only game console ever built with an integrated thermal sticker printer gets a modern homebrew stack. On the software side: a complete mini-platformer running on MAME — 8.8 fixed-point physics with asymmetric gravity, a bitmap software renderer with follow camera and offscreen sprite culling, a two-screen tile world, edge-detecting enemy AI, all at a smooth ~55 fps out of an sh-elf-gcc pipeline. On the hardware side, a printer observer overlay taps every documented MMIO write — motor phase keys, head data, enable gating — decoding only what the hardware megadoc guarantees and leaving protocol invention for when a real machine arrives. And the crown: a clean-room MAME sound device for the NEC µPD937 synth, roughly 900 lines producing the console's first emulated audio — ROM-directory parse, MIDI voice allocation, volume and pitch envelopes, sample playback, biquad tone shaping — then wired so a modern MIDI keyboard performs the 1995 chip live, all 110 of its instrument voices catalogued as musical by ear. Where the printer road finally leads is a tale for another day.",
    milestones: [
      { label: "sh-elf-gcc toolchain + hello world verified on MAME", done: true },
      { label: "Full mini-platformer: fixed-point physics, software renderer, AI at ~55 fps", done: true },
      { label: "Printer observer overlay: documented-MMIO tap with on-screen timeline", done: true },
      { label: "Clean-room µPD937 MAME sound device — the console's first emulated audio", done: true },
      { label: "Live MIDI: the 1995 synth played from a modern keyboard in real time", done: true },
      { label: "Real hardware, and the thermal printer itself — the road ahead", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked", "disasm"],
    screenshots: [],
    repo: null,
    links: [
      { label: "▶ The µPD937 synth, heard", url: "https://www.youtube.com/watch?v=IFznxIknyBg" },
    ],
  },

  /* ---- Atari Jaguar ---- */
  {
    id: "jag-ff4",
    title: "Final Fantasy IV — Atari Jaguar",
    platform: "jaguar",
    type: "porting",
    status: "ongoing",
    progress: 15,
    summary: "The maddest route in the codex: FF4 brought to the Jaguar not by rewriting it, but by transpiling the entire SNES disassembly — a custom-built 65c816→68k transpiler (all six modules green, 4.78 MB of generated assembly), a byte-perfect SNES build as the oracle, and a software SNES-PPU bridge feeding the Jaguar. The AKAO sound engine has been rebuilt to SNES fidelity: the Prelude and Edward's harp validated by ear as 'practically identical'. Current front line: the opening Red Wings flight, where Mode 7 meets a console that never had one. The tiny progress bar is honest — this is the tears-and-blood pipeline, fought one hard-won session at a time.",
    milestones: [
      { label: "Custom 65c816→68k transpiler — six modules, 4.78 MB of asm", done: true },
      { label: "Boots on Jaguar: trampoline dispatch, title screen passes", done: true },
      { label: "Full sync pipeline: NMI dispatch, pad input arriving", done: true },
      { label: "AKAO audio at SNES fidelity — validated by a musician's ear", done: true },
      { label: "Red Wings opening: Mode 7 + sprites (4 root causes fixed, validating)", done: false },
      { label: "Field, menus, battles… the mountain", done: false },
    ],
    badges: ["toolchain", "disasm", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  {
    id: "jag-lba1",
    title: "Little Big Adventure — Atari Jaguar",
    platform: "jaguar",
    type: "porting",
    status: "ongoing",
    progress: 20,
    summary: "The tenth life of LBA in this codex, and among the hardest-won: LBA1 on a 6 MB Jaguar cartridge with bank switching, rendered by a polygon rasterizer written instruction by instruction in GPU TOM assembly — four-edge clipping, Gouraud shading, spheres — until Twinsen stands correctly shaded in the Citadel and walks through multi-room scrolling at 60 fps. The crown jewel: the Jaguar's 480i interlaced mode, which no retail game ever shipped, switched on to chase 1:1 parity with the PC DOS original at 640×480. Local-only until the rights holders say yes.",
    milestones: [
      { label: "Citadel scene rendered; 134-scene cart; multi-room scroll at 60 fps", done: true },
      { label: "GPU TOM rasterizer from scratch: clipping, fill, Gouraud, spheres", done: true },
      { label: "Twinsen walkable, sprite-based body — bus contention defeated", done: true },
      { label: "640×480i interlace — a mode no retail Jaguar game ever used", done: true },
      { label: "Animations, collisions, script engine from the community fork", done: false },
      { label: "The mountain, again", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  {
    id: "jag-relics-arg",
    title: "Taming All Five — Atari Jaguar",
    platform: "jaguar",
    type: "homebrew",
    status: "ongoing",
    progress: 55,
    summary: "The deepest pipeline in the whole codex, and the one that started it: forty-five sessions of pure 68000 assembly spent making the Jaguar's five processors cooperate, one hardware quirk at a time. At its heart is a from-scratch DDA raycaster — textured first-person rooms and a corridor, four-way movement, interactive terminals — running on BigPEmu and on a real Atari Jaguar via flashcart. Around it, a technical showcase that puts every chip to work: the GPU RISC drawing a rotating wireframe hypercube from local RAM, the Blitter doing pattern fills, line work and Gouraud-shaded meshes, the Object Processor layering double-buffered sprites without a flicker, and the DSP carrying the sound — with an LPC-10 vocoder voice, a Jaguar homebrew first, in the pipeline. The real trophy is the scar tissue: OLP word-swaps, GPU code that only runs from local RAM, unsigned multiplies that return garbage on real silicon, write-posting NOPs before divides, double-buffer races against the Object Processor — the accumulated hardware lore of a machine famous for fighting back, written down lever by lever. Where these rooms ultimately lead is a tale for another day.",
    milestones: [
      { label: "Pure 68000 + RMAC pipeline; boots on BigPEmu and a real Jaguar via flashcart", done: true },
      { label: "DDA raycaster: textured first-person rooms + corridor, four-way movement, terminals", done: true },
      { label: "GPU RISC wireframe 3D from local RAM (rotating hypercube), flicker-free double-buffer", done: true },
      { label: "Object Processor sprite layers + DSP audio; 45 sessions of hardware quirks tamed", done: true },
      { label: "Blitter Gouraud finale + LPC-10 vocoder voice (a Jaguar homebrew first) — the road ahead", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked", "real-hardware"],
    screenshots: [],
    repo: null,
  },

  /* ---- Panasonic 3DO ---- */
  {
    id: "3do-omf2097",
    title: "One Must Fall: 2097 on the 3DO",
    platform: "3do",
    type: "porting",
    status: "ongoing",
    progress: 40,
    summary: "Can a 3DO run OMF's CEL engine at a playable rate? Yes: a complete 1-v-1 match vs the AI — pilot select, real movesets, throws, knockback, per-arena music, KO — built on OpenOMF and squeezed under the 32-colour PLUT cap. Version 0.1, 'playable 1v1'.",
    milestones: [
      { label: "Playable 1v1 vs AI with full scene flow", done: true },
      { label: "Data-driven movesets, throws, damage, SFX + music", done: true },
      { label: "All 10 HARs wired as fighters (2/10 so far)", done: false },
      { label: "Rounds, stun bar, arena hazards, victory poses", done: false },
    ],
    badges: ["first-boot", "toolchain"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/3do-omf2097",
  },

  {
    id: "3do-terminal",
    title: "Signal & Static — Panasonic 3DO",
    platform: "3do",
    type: "homebrew",
    status: "ongoing",
    progress: 65,
    summary: "An original interactive experience for the Panasonic 3DO in the shape of a green-phosphor computer terminal — and a deep tour of the machine's Portfolio SDK. It centres on an animated oscilloscope that tunes across frequencies, wrapped in a CRT boot sequence, a CEL-image slideshow archive, and a three-level arcade minigame — a reaction stage, a rhythm stage, and a wireframe-sphere target stage — each with its own streaming drone track and hit SFX. The engineering is where the sweat went: seven sessions of busy-wait flicker were cured the day WaitVBL was found hiding one uppercase letter away from the camelCase name the code had been searching for, unlocking the correct draw → DisplayScreen → WaitVBL → flip loop; SPORT DMA via CopyVRAMPages replaced CPU memcpy for the ~120 KB/frame background blit, dragging the minigame from unplayable to smooth; the EffectsHandler's mixer DSP only made sound once its gain knobs — silent at zero by default — were found and opened; and variable-pitch SFX were driven through sampler.dsp's 1.15 fixed-point frequency knob, which quietly demands mono samples. AIFF assets had to be padded to whole-second boundaries or the loader failed with a silent alignment error. All C89-strict, all validated on a real FZ-10 over NTSC — emulator-to-hardware FPS gap and all. What the terminal is really for is a tale for another day.",
    milestones: [
      { label: "Portfolio SDK bring-up: CEL images, terminal text, C89 pipeline, boots on a real FZ-10", done: true },
      { label: "VBL double-buffering via WaitVBL — flicker eliminated after a seven-session hunt", done: true },
      { label: "SPORT DMA background blit (CopyVRAMPages) — minigame from unplayable to smooth", done: true },
      { label: "Full audio: EffectsHandler mixer, streaming drones, variable-pitch mono SFX", done: true },
      { label: "Three-level arcade minigame with transitions; green-phosphor oscilloscope terminal", done: true },
      { label: "Final content, and where the terminal leads — the road ahead", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked", "real-hardware"],
    screenshots: [],
    repo: null,
  },

  /* ---- Sega 32X ---- */
  {
    id: "32x-lba1",
    title: "Little Big Adventure — Sega 32X",
    platform: "32x",
    type: "porting",
    status: "ongoing",
    progress: 60,
    summary: "Filed as '99% infeasible' at kickoff — 19 sessions later the real LBA1 engine runs from pure LIFE/TRACK bytecode on the mushroom. Along the way: isometric scene split across both SH-2s, a Gouraud-shaded 3D Twinsen, and an audio odyssey that ended with the 68000 driving the Genesis YM2612 directly — five empirical OPL2→FM translation rules squeezing all 33 music tracks into 55 KB instead of 10 MB of PCM. All four CPUs employed. 1.48 MB of the 4 MB cart used.",
    milestones: [
      { label: "Iso brick scene + interactive camera on dual SH-2", done: true },
      { label: "Gouraud 3D Twinsen: animations, behaviors, collisions", done: true },
      { label: "FM audio: 68000-driven YM2612, 33 tracks in 55 KB", done: true },
      { label: "Intro slides, typewriter dialogs, inventory, pickups", done: true },
      { label: "Engine pivot: real LIFE/TRACK bytecode, DoAnim/DoDir 1:1", done: true },
      { label: "Combat damage, zone dialogs, full first-scene closure", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },
  {
    id: "32x-lba2",
    title: "Little Big Adventure 2 — Sega 32X",
    platform: "32x",
    type: "porting",
    status: "ongoing",
    progress: 35,
    summary: "The sibling wager: LBA2's outdoor 3D is mostly static and flat, so how far can the LBA1/32X pipeline stretch? Interiors reuse the iso brick renderer; outdoors get a compact scene graph with frustum culling split across both SH-2s. The cube-0 opening runs from real LIFE bytecode — Twinsen and Zoe scripted, dialog on screen, hero controllable afterwards. Current front line: replacing the placeholder hero locomotion model with a faithful PERSO port.",
    milestones: [
      { label: "Interior iso scenes via the LBA1/32X pipeline", done: true },
      { label: "Outdoor static 3D, frustum cull on dual SH-2", done: true },
      { label: "Engine bring-up: LIFE bytecode + dialogs in cube 0", done: true },
      { label: "Faithful hero animation / orientation (PERSO port)", done: false },
      { label: "FM audio reuse, island selection under the 4 MB cart", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Sega Saturn ---- */
  {
    id: "saturn-explorer",
    title: "Wireframe Worlds — Sega Saturn",
    platform: "saturn",
    type: "homebrew",
    status: "ongoing",
    progress: 65,
    summary: "An original 3D exploration game built on the Sega Saturn through Jo Engine and Sega's own SGL — running on the real console, not just emulation. The player flies a freecam with spaceship inertia (fixed-point speed, damping, per-axis collision, no roll) through wireframe rooms drawn as VDP1 quads, linked by a corridor whose rollback collision avoids the classic teleport-on-entry bug. Hidden in a field of drifting noise are anamorphic tile clusters that only resolve into clean shapes from precise vantage points — a pure-perspective trick with no textures. The standout is a two-chip flex: while VDP1 rotates the 3D wireframe with the camera, VDP2 paints an independent hardware tile-plane 'digital sky' scrolling on its own axis under an atmospheric colour filter — all for zero SH-2 cycles, since scroll and tint are single VDP2 registers. Stay still too long and hitscan enemy waves close in, cleared with a laser rather than physical projectiles. Later the world opens up with a Breath-of-the-Wild reveal: a 64-quad phantom facility, visible through the walls but never enterable, graded darker with depth — sitting inside a polygon budget the game barely dents, a measured 15–25% of VDP1. Audio rides CDDA drone loops with seamless track switching over PCM stingers. All integer math, all quads, all on the metal — with real-hardware overscan quirks documented against a RetroTink capture. Where the corridors ultimately lead is a tale for another day.",
    milestones: [
      { label: "Jo Engine / SGL pipeline: ISO+CUE build, boots on a real Saturn", done: true },
      { label: "Freecam with spaceship inertia + per-axis rollback collision across linked rooms", done: true },
      { label: "Anamorphic VDP1 tile symbols resolving only from precise viewpoints", done: true },
      { label: "VDP2 hardware sky: independent scroll + colour filter at zero SH-2 cost", done: true },
      { label: "CDDA drone + PCM stingers, seamless switching; phantom-facility reveal in budget", done: true },
      { label: "Final polish, and where the corridors lead — the road ahead", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked", "real-hardware"],
    screenshots: [],
    repo: null,
  },

  /* ---- Sony PlayStation ---- */
  {
    id: "ps1-vampire-re",
    title: "Vampire: Kyūketsuki Densetsu — Translation Quest",
    platform: "ps1",
    type: "re",
    status: "ongoing",
    progress: 15,
    summary: "A quest born of friendship: a private English translation of Artdink's PS1 retelling of Dracula — Jonathan the lawyer, his fiancée Rose, Count Varaur, London — as a gift for a friend who loves vampires. Session two struck gold: the entire story turned out to be plaintext Shift-JIS, and all ~12,400 narrative characters are dumped and catalogued. The scene-script bytecode has been structurally cracked. Still embryonic, and carried out with its own etiquette: another fan translator is at work on the same game, so the plan is to reach out before going deep — and this stays personal, never a public release.",
    milestones: [
      { label: "Disc structure and containers parsed, assets classified", done: true },
      { label: "All narrative text dumped: ~12,400 chars, 607 unique kanji", done: true },
      { label: "Scene-script bytecode structurally cracked", done: true },
      { label: "Text renderer RE + reinsertion pipeline", done: false },
      { label: "The translation itself — a gift, not a release", done: false },
    ],
    badges: ["disasm"],
    screenshots: [],
    repo: null,
  },

  /* ---- Sony PlayStation 2 ---- */
  {
    id: "ps2-rhythm",
    title: "Beneath the Rhythm — PlayStation 2",
    platform: "ps2",
    type: "homebrew",
    status: "ongoing",
    progress: 55,
    summary: "An original rhythm game built from the metal up on the PlayStation 2 — and one that hides more beneath its surface than it shows. The rhythm core reads five fingers across the DualShock: shoulder taps and holds, face-button hits, stick flicks and sustains — fourteen inputs and three note types on a scrolling highway, with an in-game calibration screen, scoring, combos and progressive unlocks, all validated 1:1 between PCSX2 and a real PS2 slim. But under the notes runs a surprising amount of 3D engine: a hand-written VU1 vector pipeline doing skeletal skinning on fully-rigged models, gsKit and VU1 microcode coexisting in one binary without conflict, a free-roam 3D environment with lookAt cameras and collision, procedural particle effects, and an art-streaming pipeline threading VRAM through a linear bump allocator that punishes a single mis-ordered upload. Dozens of hard-won gotchas were paid for in full — VU1 matrix chirality, GS register-state contamination bleeding across draws, vertex-buffer stride traps, XYOFFSET centering — the kind of low-level PS2 lore rarely written down. For real-hardware players there's even a hidden tier of DualShock 2 analog-pressure sensitivity. What the rhythm layer is really guarding is a tale for another day.",
    milestones: [
      { label: "Rhythm core: 14 inputs, 3 note types, calibration, scoring, combos, unlocks", done: true },
      { label: "VU1 vector pipeline: skeletal skinning + gsKit/VU1 coexistence in one binary", done: true },
      { label: "Free-roam 3D environment: lookAt cameras, collision, world-space draw path", done: true },
      { label: "Art + audio streaming through the VRAM bump allocator; MP3 track pipeline", done: true },
      { label: "Validated 1:1 on real PS2 slim ↔ PCSX2; hidden analog-pressure tier", done: true },
      { label: "Final charts, tuning, and what waits beneath the rhythm — the road ahead", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked", "real-hardware"],
    screenshots: [],
    repo: null,
  },

  /* ---- Nintendo 64 ---- */
  {
    id: "n64-lba2",
    title: "Little Big Adventure 2 — Nintendo 64",
    platform: "n64",
    type: "porting",
    status: "ongoing",
    progress: 65,
    summary: "The Wii U port's big-endian twin: LBA2 on libdragon with no leaked SDK, the software renderer presented through the RDP as a palette blit, and a MIPS unaligned-access emulator written into the exception handler to tame the engine's packed data. The game runs — 58 VPS in Twinsen's house, exteriors working, 12-voice SFX on the RSP mixer and Opus music streaming from a 45 MB ROM.",
    milestones: [
      { label: "Docker toolchain — full engine compiles and boots on Ares", done: true },
      { label: "Game runs: first scene, dialogs, scripts, input complete", done: true },
      { label: "Unaligned-access emulator in the MIPS exception handler", done: true },
      { label: "Audio: 12-voice RSP SFX + streamed Opus music, in-game", done: true },
      { label: "RSP crash on scene change (double-buffered TLUT fix to verify)", done: false },
      { label: "Voice-over repack under 64 MB, SRAM saves, FMV, polish", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Sega Dreamcast ---- */
  {
    id: "dc-lba2",
    title: "Little Big Adventure 2 — Dreamcast",
    platform: "dreamcast",
    type: "porting",
    status: "bossfight",
    progress: 75,
    summary: "The original 1997 Adeline engine compiled for the Dreamcast via KallistiOS: first island playable to completion on Flycast with FMV, music, voices, VMU saves. The boss fight: on real hardware boot stalls after the EA logo — first UART capture has pinned a render-side crash, diagnosis underway.",
    milestones: [
      { label: "Engine boots: intro FMV, menu, gameplay on Flycast", done: true },
      { label: "First island completable; second island loads", done: true },
      { label: "Audio streams + VMU save/load", done: true },
      { label: "BOSS: real-Dreamcast boot blocker (UART diagnosis)", done: false },
      { label: "Full playthrough validation", done: false },
    ],
    badges: ["first-boot", "toolchain"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/dc-lba2",
  },

  {
    id: "dc-ff8",
    title: "Final Fantasy VIII — Dreamcast",
    platform: "dreamcast",
    type: "porting",
    status: "ongoing",
    progress: 40,
    summary: "The game the Dreamcast never got, rebuilt the honest way: a C++ reimplementation on KallistiOS that executes FF8's own data — the field scenes run their authentic script bytecode (the Balamb infirmary plays out its real 1,960-op program), stats come from kernel.bin, and the physical damage formula is transcribed from byte-matching decompiled code. Triple Triad is fully playable and 'unsettlingly identical'; the whole party walks in 3D at 60 fps inside the real painted backdrops with depth occlusion; battle monsters animate on real 3D stages with authentic UI art. Includes an original RE contribution: the field bone-rotation decode, verified against the PS1 assembly nobody had decompiled. Bring-your-own-assets throughout. And parked in a drawer: Chocobo World running its original ARM ROM on the VMU via a home-made PocketStation emulator.",
    milestones: [
      { label: "Triple Triad 1:1 — all rules, authentic art, SFX and BGM", done: true },
      { label: "Field: party in 3D at 60 fps inside real backdrops, depth-occluded", done: true },
      { label: "Field VM: authentic JSM bytecode executed (infirmary scene live)", done: true },
      { label: "Battle slice: real formulas, monster stats, stages, authentic UI", done: true },
      { label: "FMV pipeline proven (RoQ streaming with audio)", done: true },
      { label: "Magic/GF effect compositor — the frontier nobody has decompiled", done: false },
      { label: "Enemy-AI bytecode interpreter, main menu, VMU saves", done: false },
    ],
    badges: ["toolchain", "first-boot", "disasm", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  {
    id: "dc-mi3",
    title: "The Curse of Monkey Island — Dreamcast",
    platform: "dreamcast",
    type: "porting",
    status: "bossfight",
    progress: 70,
    summary: "ScummVM bug #6008: SCUMM v8 games have never run on the Dreamcast — a wall standing for some twenty years. This quest broke it. Built on the alternate KallistiOS backend, the memory war was won lever by lever: 3.5 MB of GUI TrueType fonts evicted, a 600 KB buffer upstream allocates by mistake removed, costumes flushed before cutscenes — while a concurrent CD-I/O race and a 32 KB thread-stack overflow (masquerading as a dozen different corruptions) were root-caused and fixed. Result: The Curse of Monkey Island boots, plays its intro FMV with sound, and renders real gameplay — Guybrush and Wally in the ship hold — at 52 fps on a stock 16 MB Dreamcast, the deepest CMI has ever run on the console. The boss: a main-thread hang right before the first spoken line.",
    milestones: [
      { label: "dcalt/KOS ScummVM built from source with SCUMM v8 enabled", done: true },
      { label: "Boots in 16 MB: theme-font diet, intro, difficulty select, audio", done: true },
      { label: "Intro FMV with sound in sync + chapter card with music", done: true },
      { label: "CD-I/O race and thread-stack corruption root-caused and fixed", done: true },
      { label: "Real gameplay rendered at 52 fps — past the historic wall", done: true },
      { label: "BOSS: main-thread hang before the first dialogue line", done: false },
      { label: "Full playability pass, upstreamable fixes, real hardware", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  {
    id: "dc-shmup",
    title: "Squeezing the Dreamcast — a Music-Synced Shmup",
    platform: "dreamcast",
    type: "homebrew",
    status: "ongoing",
    progress: 50,
    summary: "An original beat-synced shoot-'em-up built to push the Dreamcast's PVR to the metal — and its engine has a two-act story. First a full port of the modern Simulant C++ engine to KallistiOS and GCC 15, running clean on real hardware; then, when commercial-game screenshots set a higher bar, a pivot to a custom mini-engine talking straight to the PVR through KOS, hitting a locked 60 fps across all three hardware lists. The road there was a masterclass in Dreamcast graphics: a discovery that parked bullets behind the camera were still being submitted every frame led to explicit frustum culling that cut scene traversal from 22 ms to 3 ms; a GLdc fast-path bypassing the normal submit for direct SH4 store-queue writes to the PVR (swap-buffers 22 ms → 12 ms); GLB models fed straight to the tile accelerator; and a real-hardware debugging saga chased over a serial cable, where a TA vertex-buffer overflow and a VRAM bank-boundary crash were root-caused with on-screen and dbgio probes, then tamed with mesh decimation and a VQ-texture fallback plan. Music drives all of it: tracks beat-analysed to the decimal BPM, boss beams pulsing capsule-shaped on the downbeat, per-element particle systems, fights that run until the song ends. A tutorial stage and an elemental boss stage already play — the remaining stages, and the reason behind them, are a tale for another day.",
    milestones: [
      { label: "Simulant C++ engine ported to KallistiOS / GCC 15, clean on real hardware", done: true },
      { label: "Pivot to a custom PVR-direct mini-engine — locked 60 fps, all three TA lists", done: true },
      { label: "Frustum culling + GLdc store-queue fast-path (22→12 ms swap, 22→3 ms traverse)", done: true },
      { label: "Real-HW debug over serial: TA vbuf overflow + VRAM bank crash root-caused", done: true },
      { label: "Beat-synced combat: decimal-BPM analysis, pulsing beams, elemental particles", done: true },
      { label: "Remaining stages and a full real-hardware pass — the road ahead", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Nintendo Wii U ---- */
  {
    id: "wiiu-lba2",
    title: "Little Big Adventure 2 — Wii U",
    platform: "wiiu",
    type: "porting",
    status: "completed",
    progress: 100,
    summary: "V1.0: the original 1997 Adeline source running natively on the Wii U — completed start to finish on real hardware, full story, all cutscenes and FMVs, 50–80 fps, native AX audio, GamePad touch panel for behaviours and spells, saves with on-screen keyboard. ~99.9% parity with the original.",
    milestones: [
      { label: "Big-endian PowerPC port of the DOS/Win95 engine", done: true },
      { label: "FMV streaming, AX audio, saves, full GamePad + touch", done: true },
      { label: "Complete playthrough validated on real hardware", done: true },
      { label: "Post-release polish (controls tuning, touch labels)", done: false },
    ],
    badges: ["released", "real-hardware", "first-boot", "toolchain"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/wiiu-lba2",
  },

  /* ---- Philips CD-i ---- */
  {
    id: "cdi-bringup",
    title: "CD-i Homebrew Bring-Up",
    platform: "cdi",
    type: "homebrew",
    status: "ongoing",
    progress: 25,
    summary: "First steps on Philips' great curiosity. The Microware OS-9 toolchain — xcc compiler, l68 linker, fixmod, and a 16-bit DOS disc-mastering tool — resurrected inside Docker with 25-second builds; boot confirmed under emulation; and a hello world painting CLUT7 colour bands through the MCD212 video chip, delivered as properly-formed OS-9 modules rather than bare-metal tricks. TwBurn's open-source Nobelia serves as the end-to-end oracle proving the road exists. Where this road leads is a tale for another day.",
    milestones: [
      { label: "Feasibility recon: toolchain, emulators, asset pipeline mapped", done: true },
      { label: "Docker toolchain: xcc + l68 + fixmod + DOS mastering, 25 s builds", done: true },
      { label: "Boot confirmed under CD-i emulation", done: true },
      { label: "Hello world on screen: CLUT7 bands via the MCD212", done: true },
      { label: "A real application — and where it leads is another story", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Amiga CD32 ---- */
  {
    id: "cd32-lba1",
    title: "Little Big Adventure — Amiga CD32",
    platform: "cd32",
    type: "porting",
    status: "ongoing",
    progress: 35,
    summary: "The 1994 Adeline engine squeezed into 2 MB of chip RAM on a big-endian 68020: boots from CD, Akiko C2P rendering, and a perfect main menu at native 320×240 — where a key discovery (the engine's projection is hard-coded) means the native view IS the original 1994 view. Current front line: a crash in the object renderer, first scene almost in sight.",
    milestones: [
      { label: "M0: Akiko C2P HQR viewer boots from ISO", done: true },
      { label: "M1: full engine compiles, boots, Adeline logo on screen", done: true },
      { label: "M2: native 320×240 render — menu perfect, 2 MB RAM wall beaten", done: true },
      { label: "First in-game scene (object-renderer crash under diagnosis)", done: false },
      { label: "M4: Paula SFX, CDDA music, NVRAM saves", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  {
    id: "cd32-workbench-anthology",
    title: "The Workbench Anthology — Amiga CD32",
    platform: "cd32",
    type: "homebrew",
    status: "ongoing",
    progress: 60,
    summary: "A bootable Amiga Workbench packed with original CD32 homebrew, built on the Bartman m68k GCC toolchain — no libgcc, no floats, pure integer and fixed-point. The centrepiece is a genuine hardware showcase: a 256-colour AGA plasma demo driving the CD32's signature Akiko chunky-to-planar register at $B80038, its 8-longword write-then-read protocol reverse-engineered from WinUAE's akiko.cpp — proof that the real bottleneck is 68020 fill rate, not the C2P silicon. Around it sit several playable programs: a circular Breakout with paddle physics and level progression, a sprite-based mini-RPG, and a pseudo-3D skeet-shooting game with polygon rendering — plus CDXL video, IFF imagery through MultiView, and CDDA streamed asynchronously through cd.device. The low-level Amiga lore is all here: copper-list writes that bus-error on real hardware unless cast just so, a WBStartup handshake for launching from the desktop, a seven-button CD32 pad read through ReadJoyPort with its first-call priming quirk, and an input handler dropped down to m68k assembly where the C path wouldn't reach. What all these programs are quietly part of is a tale for another day.",
    milestones: [
      { label: "Bartman m68k GCC pipeline: bootable Workbench CD, WBStartup app launch", done: true },
      { label: "Akiko C2P demo: 256-colour AGA plasma via $B80038, protocol RE'd from WinUAE", done: true },
      { label: "Playable programs: circular Breakout, sprite mini-RPG, pseudo-3D skeet shooting", done: true },
      { label: "Media stack: CDXL video, IFF imagery, async CDDA through cd.device", done: true },
      { label: "CD32 seven-button pad via ReadJoyPort + m68k-asm input handler", done: true },
      { label: "Tying the anthology together — the road ahead", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked", "disasm"],
    screenshots: [],
    repo: null,
  },

  /* ---- Nintendo DS ---- */
  {
    id: "ds-lba1",
    title: "Little Big Adventure — Nintendo DS",
    platform: "ds",
    type: "porting",
    status: "ongoing",
    progress: 70,
    summary: "LBA1 playable on the DS at a locked 50 fps: the real engine ITCM/ARM-optimized down to 6.5 ms per 3D actor, persistent saves on SD, SFX and voice acting through the hardware audio channels — and a custom touch HUD on the second screen with live health, money and one-tap behaviour switching. Fits a stock 4 MB DS with 1.5 MB to spare.",
    milestones: [
      { label: "Boots to gameplay: logos, menu, intro, first scene", done: true },
      { label: "50 fps gameplay after ITCM/DTCM optimization campaign", done: true },
      { label: "Persistent savegames on SD card", done: true },
      { label: "SFX + dialog voices via ARM7 hardware channels", done: true },
      { label: "Touch HUD on second screen with live stats", done: true },
      { label: "Music, remaining islands' voices, full-game validation", done: false },
    ],
    badges: ["real-hardware", "toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Game Boy Advance ---- */
  {
    id: "gba-lba1-poc",
    title: "Little Big Adventure — GBA (Proof of Concept)",
    platform: "gba",
    type: "porting",
    status: "ongoing",
    progress: 30,
    summary: "Not a demake: the genuine LBA1 engine — LIFE/TRACK script interpreters, brick collisions, 3D actor animation — running the opening asylum cell on a 16.78 MHz ARM7TDMI with 256 KB of RAM. A measured 4.7× optimization journey (ROM waitstates, IWRAM/ARM hot code, radix painter sort) took it from 3.5 to 16.5 fps, dialog with the nurse included.",
    milestones: [
      { label: "Real engine slice on ARM: scene, scripts, collisions", done: true },
      { label: "Twinsen fully animated (180 verts, Gouraud rasterizer)", done: true },
      { label: "Dialog system with authentic TEXT.HQR data", done: true },
      { label: "3.5 → 16.5 fps measured optimization campaign", done: true },
      { label: "Scenes beyond cube 0, audio", done: false },
    ],
    badges: ["first-boot", "toolchain"],
    screenshots: [
      "assets/gba-lba/1-bricks.png",
      "assets/gba-lba/2-twinsen.png",
      "assets/gba-lba/3-engine.png",
      "assets/gba-lba/4-nurse.png",
    ],
    repo: null,
  },

  /* ---- Super Nintendo ---- */
  {
    id: "snes-rudra-re",
    title: "Rudra no Hihō — Text & Sound RE",
    platform: "snes",
    type: "re",
    status: "ongoing",
    progress: 45,
    summary: "Decoding the Japanese text system of Square's Treasure of the Rudras: custom 2-byte kanji encoding, DTE dictionaries, inline furigana — ~286 of ~730 kanji codes identified. A second track cracked the AKAO sound engine, ending in a fully static SPC extractor that rips every song from ROM tables alone, no emulator needed.",
    milestones: [
      { label: "Kana layout, control codes, DTE dictionary decoded", done: true },
      { label: "AKAO sound engine + emulator-free static SPC ripper", done: true },
      { label: "Kanji table: 286 / ~730 codes identified", done: false },
    ],
    badges: ["disasm", "audio-unlocked"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/snes-rudranohihou-re",
  },

  {
    id: "snes-lba1-poc",
    title: "Little Big Adventure — SNES + SuperFX (PoC)",
    platform: "snes",
    type: "porting",
    status: "ongoing",
    progress: 55,
    summary: "The real LBA1 engine on a 65816, with a SuperFX GSU composing the isometric scene straight into SNES bitplane format — driven by hand-written GSU assembly built with a from-scratch Python mini-assembler. The prison's upper floor is alive: 23 actors, LIFE/TRACK scripts and zones running, the hover platform flying to the hero on cue, pixel-exact sprite occlusion behind the cell fence.",
    milestones: [
      { label: "Feasibility study + M0: prison scene in Mode 3, budgets validated", done: true },
      { label: "M1: SuperFX compositor pixel-perfect vs reference + camera pan", done: true },
      { label: "M2: engine alive in C — Twinsen walks and collides (~30 fps hero-only)", done: true },
      { label: "M3: full scene — 23 actors, scripts, zones, GSU sprite-clip occlusion", done: true },
      { label: "Dialog textbox + performance pass (11–25 fps with NPCs today)", done: false },
      { label: "M4: true flat-3D hero rendered by the GSU · M5: SPC700 audio", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Smaky ---- */
  {
    id: "smaky-ff1",
    title: "Final Fantasy — Smaky (The Anachronistic Remake)",
    platform: "smaky",
    type: "porting",
    status: "accepted",
    progress: 10,
    summary: "The codex's most gloriously improbable quest: what if Square had owned a Smaky instead of a Famicom? FF1 remade for the Swiss school computer — hardware released three years before the game, yet mightier than a NES: a 68000, a full megabyte of RAM, a real keyboard, and 640×400 of green phosphor. No bank switching, no text compression — the challenge is making tiles readable in pure monochrome dithering. The Smaky 100's innards were never publicly documented, so the port targets a 'fantasy console' faithful to every authentic spec. Toolchain proven, the FF1 font already glows green. An informal race is on against the ColecoVision and 7800 siblings for the first shippable demo — and this machine from a stranger timeline may yet play a larger role in tales to come.",
    milestones: [
      { label: "Spec sprint: authentic Smaky 100 specs triangulated from Swiss sources", done: true },
      { label: "Toolchain + green-phosphor harness proven (68000 hello)", done: true },
      { label: "FF1 font pipeline rendering on the mono display", done: true },
      { label: "Party generation, 80×60 overworld, dithered tile art", done: false },
      { label: "First shippable demo — the FF1 sibling race", done: false },
    ],
    badges: ["toolchain"],
    screenshots: [],
    repo: null,
  },

  /* ---- The PC ---- */
  {
    id: "pc-silver-re",
    title: "Silver (1999) — Engine Archaeology, toward Co-op",
    platform: "pc",
    type: "re",
    status: "ongoing",
    progress: 55,
    summary: "A full dig into Spiral House's 1999 action-RPG: every scene format decoded (308 backgrounds with pixel-perfect depth occlusion), the rolling-XOR dialog cipher cracked (2,828 lines recovered), character models rebuilt with skeletons and animations — down to discovering the on-disk quaternions are stored (z,x,y,w) — and the walkmesh of all 287 scenes parsed. The Dreamcast build was disassembled too, to settle an input-system mystery. End goal: a code-patch mod bringing co-op play to the 3-member party. Documentation and methodology only — no assets, no code dumps; the game is still on sale.",
    milestones: [
      { label: "All 308 backgrounds + depth/occlusion decoded pixel-perfect", done: true },
      { label: "Dialog cipher cracked — 2,828 lines recovered", done: true },
      { label: "Models, textures, UVs, skeletons, animations fully decoded", done: true },
      { label: "Walkmesh / pathfinding graph parsed for all 287 scenes", done: true },
      { label: "Input system mapped — incl. Dreamcast SH-4 disassembly cross-check", done: true },
      { label: "Co-op mode mod via code patches", done: false },
    ],
    badges: ["disasm", "toolchain"],
    screenshots: [],
    repo: null,
  },

  {
    id: "pc-tle-re",
    title: "The Last Express (1997) — Clockwork of the Orient Express",
    platform: "pc",
    type: "re",
    status: "ongoing",
    progress: 60,
    summary: "Digging into Jordan Mechner's real-time masterpiece through its modern re-release — a cocos2d-x shell around the nearly intact 1997 game. All major formats decoded: backgrounds, audio, the subtitle system with its custom bitmap font (perfect text in five languages), actor-sprite RLE, and the NIS cutscene containers — whose engine turned out to be byte-identical to the 1997 original. The character-AI virtual machine was mapped in the exe, down to reversing the exact trigger of the infamous 'August finds the corpse' game over, cross-confirmed against ScummVM at three matching call sites. Documentation and tooling only — the game is still on sale.",
    milestones: [
      { label: "Backgrounds, audio, subtitles + custom font fully decoded", done: true },
      { label: "SEQ actor sprites decoded (all RLE packing variants)", done: true },
      { label: "NIS cutscene containers + sprite decode solved", done: true },
      { label: "Entity VM mapped; the 1009 game-over trigger reversed", done: true },
      { label: "Fade sprites, NIS playback timing, train scene graph", done: false },
    ],
    badges: ["disasm", "toolchain"],
    screenshots: [],
    repo: null,
  },

  {
    id: "pc-risinglands-wrap",
    title: "Rising Lands — Zero-Friction Compatibility Layer",
    platform: "pc",
    type: "tooling",
    status: "ongoing",
    progress: 85,
    summary: "The codex's only time-reversed port: instead of carrying a game back to old silicon, this carries Microïds' 1997 RTS forward to Windows 11 — no drivers, no mounted ISO, no physical CD. A drop-in winmm.dll proxy, reverse-engineered from the game's own MCI command strings, replays the CD soundtrack from OGG files and fakes the disc's presence; DDrawCompat cures the palette; a tiny launcher pins the Pentium-era timing loop to one core. The deep cut: a savage in-game crash root-caused with a vectored-exception logger and trampoline hooks down to a mission file hard-wired to the CD path — fixed with a redirect-on-failure file hook that cures the whole class. Mission 1 confirmed fully playable, one-click installer built. Bring your own game.",
    milestones: [
      { label: "winmm proxy: MCI→OGG music + CD-presence faking", done: true },
      { label: "Video and timing: DDrawCompat, single-core pinning, DPI manifest", done: true },
      { label: "In-game crash root-caused (CD-hardwired path) and fixed", done: true },
      { label: "v1.0 one-click installer; mission 1 fully playable", done: true },
      { label: "Full 25-mission campaign validation", done: false },
    ],
    badges: ["toolchain", "disasm"],
    screenshots: [],
    repo: null,
  },

  {
    id: "pc-replay-vault",
    title: "The Replay Vault — Childhood Titles Revived",
    platform: "pc",
    type: "tooling",
    status: "ongoing",
    progress: 80,
    summary: "A gentler kind of quest: not forcing games onto impossible hardware, but bringing the titles of an Italian childhood back to life on modern machines — and actually replaying them, start to finish. Each one its own puzzle: Tip Top (Director 5 + QuickTime) solved through Mac OS 9 emulation after ScummVM fell short; RAI's Stellaris (16-bit ToolBook + Indeo video) coaxed onto Windows 11 through otvdm and codec archaeology; Coktel Vision's A.J.'s World running under ScummVM; QBasic Gorillas reborn in DOSBox-X — complete with a custom amber-monitor GLSL shader for full 1991 flavour; and AEnigmatica, a 1998 puzzle CD that turned out to be a Java 1.1 app with hardcoded JDK quirks, still resisting. Bonus escapade: Tip Top booted natively on an emulated Bandai Pippin, AppleJack pad and all.",
    milestones: [
      { label: "Tip Top — 100% playable via SheepShaver / Mac OS 9", done: true },
      { label: "Stellaris: Sfida a StarCity — on Win11 via otvdm + Indeo codecs", done: true },
      { label: "A.J.'s World of Discovery — running under ScummVM", done: true },
      { label: "Gorillas + Battle Bugs — DOSBox-X, amber-phosphor shader included", done: true },
      { label: "AEnigmatica — the Java 1.1 sphinx still guards her riddle", done: false },
      { label: "Tip Top on the Pippin — boots natively; cutscene boss remains", done: false },
    ],
    badges: ["toolchain"],
    screenshots: [],
    repo: null,
  },

  /* ---- The Chip Forge ---- */
  {
    id: "chiproll",
    title: "ChipRoll — Piano Roll for Chip Music",
    platform: "forge",
    type: "tooling",
    status: "ongoing",
    progress: 85,
    summary: "A browser piano roll that lets musicians write for the NES, Atari TIA and POKEY the way they'd write anything else: DAW-style grid, MIDI import with auto BPM stretch, live MIDI recording, chip-accurate intonation feedback, and song-aware exports straight to FamiTracker text and ca65 assembly.",
    milestones: [
      { label: "NES + TIA + POKEY engines with pattern/song sequencing", done: true },
      { label: "MIDI import pipeline + Web MIDI live recording", done: true },
      { label: "Song-aware exports: FamiTracker, ca65, chip-native", done: true },
      { label: "POKEY v2 (16-bit joins, alt clocks), MusicXML import", done: false },
    ],
    badges: ["released", "audio-unlocked"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/chiproll",
  },
];
