/* ============================================================
   SILICON RELICS — data file
   This is the ONLY file content sweeps need to touch.
   Sweep 1 (2026-07-17): all published GitHub repos.
   ============================================================ */

const SITE = {
  tagline: "A living codex of homebrew, reverse engineering and porting quests across retro consoles — from the famous to the forgotten. A human + LLM collaboration, named openly.",
  updated: "2026-07-17",
};

/* Rarity reflects how obscure / undocumented the platform is.
   common → well-trodden ground … legendary → almost nobody has walked here. */
const RARITIES = {
  common:    { label: "Common Relic" },
  uncommon:  { label: "Uncommon Relic" },
  rare:      { label: "Rare Relic" },
  epic:      { label: "Epic Relic" },
  legendary: { label: "Legendary Relic" },
};

const TYPES = {
  homebrew: "Homebrew",
  porting:  "Porting",
  re:       "Reverse Eng.",
  tooling:  "Tooling",
};

const STATUSES = {
  accepted:  { label: "Quest Accepted", cls: "st-accepted" },
  ongoing:   { label: "In Progress",    cls: "st-ongoing" },
  bossfight: { label: "Boss Fight",     cls: "st-bossfight" },
  completed: { label: "Quest Complete", cls: "st-completed" },
};

const BADGES = {
  "first-boot":     { icon: "🕯️", label: "First Boot",            desc: "The relic drew breath: first successful boot of custom code." },
  "real-hardware":  { icon: "⚙️", label: "Runs on Real Hardware", desc: "Verified on the physical machine, not just emulation." },
  "audio-unlocked": { icon: "🎵", label: "Audio Unlocked",         desc: "Sound is alive on the platform." },
  "disasm":         { icon: "📜", label: "Scrolls Deciphered",     desc: "Significant disassembly / reverse engineering milestone." },
  "toolchain":      { icon: "🔨", label: "Forge Built",            desc: "A working toolchain / build pipeline was forged." },
  "released":       { icon: "🏆", label: "Released",               desc: "Shipped as a finished, usable release." },
  "world-first":    { icon: "🌍", label: "World First",            desc: "A documented first — nobody had done this before." },
};

/* Console generation labels for the "By Generation" view.
   90+ are special timeless groups, rendered after the console generations:
   90 = the PC (any era), 99 = the Forge (tools). */
const GENERATIONS = {
  2: { num: "II",   era: "1976 – 1983" },
  3: { num: "III",  era: "1983 – 1987" },
  4: { num: "IV",   era: "1987 – 1993" },
  5: { num: "V",    era: "1993 – 1998" },
  6: { num: "VI",   era: "1998 – 2005" },
  7: { num: "VII",  era: "2005 – 2012" },
  8: { num: "VIII", era: "2012 – 2020" },
  90: { num: "PC", title: "The Home Turf", era: "IBM PC & compatibles, 1981 → today" },
  91: { num: "✦",  title: "The Wunderkammer", era: "machines from stranger timelines" },
  99: { num: "∞",  title: "The Timeless Forge", era: "tools that serve the relics" },
};

/* ---------- Platforms (the Relics) ---------- */

const PLATFORMS = [
  {
    id: "coleco",
    name: "ColecoVision",
    maker: "Coleco",
    year: 1982,
    gen: 2,
    rarity: "uncommon",
    blurb: "1982's arcade-at-home wonder: a TMS9918 VDP, a Z80, and 1 KB of RAM — until the Super Game Module bolts on and suddenly there's room to dream much bigger.",
  },
  {
    id: "7800",
    name: "Atari 7800",
    maker: "Atari",
    year: 1986,
    gen: 3,
    rarity: "rare",
    blurb: "Atari's what-if console: no tilemaps, no sprite limits — just MARIA and her display lists, a 6502 heart, and a POKEY on the cartridge when you need real music.",
  },
  {
    id: "gx4000",
    name: "Amstrad GX4000",
    maker: "Amstrad",
    year: 1990,
    gen: 4,
    rarity: "epic",
    blurb: "Amstrad's ninety-day disaster: a CPC Plus in console clothing — Z80, ASIC hardware sprites, a 4096-colour palette — sunk by its own launch catalogue in a single Christmas.",
  },
  {
    id: "vis",
    name: "Tandy / Memorex VIS",
    maker: "Tandy · Memorex",
    year: 1992,
    gen: 4,
    rarity: "legendary",
    blurb: "The Video Information System: a CD console running Microsoft Modular Windows 3.1 on a 12 MHz 80286, with OPL3 FM synthesis. So forgotten even its ghosts need directions — now it runs raycasters.",
  },
  {
    id: "hyperscan",
    name: "Mattel HyperScan",
    maker: "Mattel",
    year: 2006,
    gen: 7,
    rarity: "legendary",
    blurb: "RFID trading cards, an S+Core CPU with an unmaintained compiler, zero storage, no SDK, no scene, discontinued within a year. The deepest public documentation of this machine lives in these quests.",
  },
  {
    id: "pippin",
    name: "Bandai Pippin @WORLD",
    maker: "Apple · Bandai",
    year: 1996,
    gen: 5,
    rarity: "legendary",
    blurb: "A stripped-down Macintosh sold as a console — PowerPC 603, Mac OS 7.5 fork, a GeoPort modem as its only road to the Internet. Barely documented, barely emulated.",
  },
  {
    id: "ngpc",
    name: "Neo Geo Pocket Color",
    maker: "SNK",
    year: 1999,
    gen: 5,
    rarity: "rare",
    blurb: "SNK's fierce 16-bit handheld (TLCS-900/H), with a proprietary Toshiba toolchain held together by decades-old links — and a link cable no emulator had ever spoken, on either side.",
  },
  {
    id: "jaguar",
    name: "Atari Jaguar",
    maker: "Atari",
    year: 1993,
    gen: 5,
    rarity: "epic",
    blurb: "Atari's last stand: 'do the math', five processors that barely speak to each other, and a 68000 that was only ever meant to be the janitor — yet ends up doing most of the work.",
  },
  {
    id: "3do",
    name: "Panasonic 3DO",
    maker: "The 3DO Company · Panasonic",
    year: 1993,
    gen: 5,
    rarity: "epic",
    blurb: "The ambitious 1993 CD console of coded CELs, 32-colour PLUTs and no float runtime. A small modern devkit keeps the forge lit.",
  },
  {
    id: "32x",
    name: "Sega 32X",
    maker: "Sega",
    year: 1994,
    gen: 5,
    rarity: "rare",
    blurb: "Sega's ill-fated mushroom: two SH-2s bolted on top of a Genesis that still has its 68000 and Z80 underneath. Four CPUs, 4 MB of cart, and a short, angry life — all four processors get put to work here.",
  },
  {
    id: "ps1",
    name: "Sony PlayStation",
    maker: "Sony",
    year: 1994,
    gen: 5,
    rarity: "common",
    blurb: "The grey box that redefined everything — and the best-charted territory in all of romhacking. For a kid who only had a PC, this was the stuff of playground legend.",
  },
  {
    id: "n64",
    name: "Nintendo 64",
    maker: "Nintendo",
    year: 1996,
    gen: 5,
    rarity: "uncommon",
    blurb: "93.75 MHz of big-endian MIPS, 8 KB of data cache, high-latency RDRAM — and libdragon, the open-source toolchain that made its homebrew scene bloom without a single leaked SDK.",
  },
  {
    id: "dreamcast",
    name: "Sega Dreamcast",
    maker: "Sega",
    year: 1998,
    gen: 6,
    rarity: "uncommon",
    blurb: "Sega's swan song and homebrew's favourite harbour — KallistiOS territory, VMU saves, and an SH4 that rewards careful code.",
  },
  {
    id: "wiiu",
    name: "Nintendo Wii U",
    maker: "Nintendo",
    year: 2012,
    gen: 8,
    rarity: "uncommon",
    blurb: "The dual-screen underdog: big-endian PowerPC, a GamePad with a touch panel, and a homebrew scene that never gave up on it.",
  },
  {
    id: "snes",
    name: "Super Nintendo",
    maker: "Nintendo",
    year: 1990,
    gen: 4,
    rarity: "common",
    blurb: "The 16-bit king — common as relics go, but its Japanese text engines and sound drivers still guard secrets worth deciphering.",
  },
  {
    id: "cd32",
    name: "Amiga CD32",
    maker: "Commodore",
    year: 1993,
    gen: 5,
    rarity: "rare",
    blurb: "Commodore's last gamble: an Amiga 1200 heart in a CD console, 2 MB of chip RAM total, and the Akiko chip doing chunky-to-planar. Every kilobyte is negotiated.",
  },
  {
    id: "ds",
    name: "Nintendo DS",
    maker: "Nintendo",
    year: 2004,
    gen: 7,
    rarity: "common",
    blurb: "Two screens, two ARM CPUs, 4 MB of RAM and a touch panel begging to become a HUD. One of homebrew's best-loved homes.",
  },
  {
    id: "gba",
    name: "Game Boy Advance",
    maker: "Nintendo",
    year: 2001,
    gen: 6,
    rarity: "common",
    blurb: "A 16.78 MHz ARM7TDMI with 256 KB of work RAM — the pocket console that keeps saying yes to things it really shouldn't be able to run.",
  },
  {
    id: "pc",
    name: "The PC",
    maker: "IBM PC & compatibles",
    year: "1981 → today",
    gen: 90,
    rarity: "common",
    blurb: "Not obscure hardware — the childhood machine itself. Here the relics are the games: late-90s engines with debug symbols left inside, ciphers to crack, and party systems waiting to become something more.",
  },
  {
    id: "smaky",
    name: "Smaky 100",
    maker: "Epsitec · Lausanne",
    year: 1984,
    gen: 91,
    rarity: "legendary",
    blurb: "The Swiss school computer: a 68000 with green-phosphor 640×400, multitasking PSos in 1983, roughly 1,500 units ever built — for classrooms of French-speaking Switzerland. Yes, really.",
  },
  {
    id: "forge",
    name: "The Chip Forge",
    maker: "Browser-based · no install",
    year: 2026,
    gen: 99,
    rarity: "common",
    blurb: "Not a console: the workbench. Tools forged in the browser to serve the other relics — and the musicians who write for them.",
  },
];

/* ---------- Projects (the Quests) ---------- */

const PROJECTS = [

  /* ---- ColecoVision ---- */
  {
    id: "coleco-ff1",
    title: "Final Fantasy — ColecoVision",
    platform: "coleco",
    type: "porting",
    status: "ongoing",
    progress: 45,
    summary: "The 1987 NES RPG on 1982 hardware — a port nobody has ever attempted. Super Game Module and MegaCart banking make it possible; the TMS9918's color limits are beaten with per-row dominant colors plus sprite accent overlays, reaching visually NES-parity battle characters. All 24 songs extracted byte-exact from the disassembly onto the AY-3-8910. The twist versus the 7800 sibling: this port deliberately fixes Square's spell bugs — while preserving beloved quirks like the Finger Point peninsula, byte-exact. Overworld, Coneria and battle already loop under multi-bank.",
    milestones: [
      { label: "Toolchain + SGM bring-up — FF1 Fighter walks on Coleco", done: true },
      { label: "Overworld at 60 Hz with discrete tile movement", done: true },
      { label: "Audio: AY-3-8910 validated, 24 songs byte-exact", done: true },
      { label: "Battle screen at visual NES-parity (per-row colors + OAM accents)", done: true },
      { label: "MegaCart multi-bank architecture, OW+town+battle loop", done: true },
      { label: "Full battle engine with intent-fixed spells; 3 banking bugs open", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Atari 7800 ---- */
  {
    id: "7800-ff1",
    title: "Final Fantasy — Atari 7800",
    platform: "7800",
    type: "porting",
    status: "ongoing",
    progress: 50,
    summary: "The 1987 NES original rebuilt on Atari's forgotten console, working straight from the FF1 disassembly with a strict NES-parity policy — Square's original bugs cataloged, and fixable by choice. MARIA display lists replace the NES tilemaps, the toroidal overworld smooth-scrolls, Coneria has its real NPC dialogs and shops, and 4-character battles run with authentic stats, magic and enemy data — up to a playable Garland fight with his true sprite. The soundtrack pipeline runs through ChipRoll to POKEY: the Forge serving the quest. Target: a combat demo to the Pravoka bridge, on real hardware via modern flash carts.",
    milestones: [
      { label: "MARIA rendering foundation: display lists, metatiles, smooth scroll", done: true },
      { label: "Toroidal overworld with tile-locked movement and player sprite", done: true },
      { label: "Coneria: town maps, disasm-faithful NPC dialogs, shop data", done: true },
      { label: "Battle engine: 4-character rounds, magic, items, party targeting", done: true },
      { label: "Garland fight playable — real stats, real sprite", done: true },
      { label: "Demo-with-combat to the Pravoka bridge · full POKEY soundtrack", done: false },
    ],
    badges: ["toolchain", "first-boot", "disasm", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Amstrad GX4000 ---- */
  {
    id: "gx4000-jetpack",
    title: "Jetpack — Amstrad GX4000",
    platform: "gx4000",
    type: "porting",
    status: "ongoing",
    progress: 30,
    summary: "Adam Pedersen's 1993 DOS classic rebuilt for Amstrad's most famous flop. No source code exists: the 234 tiles and all 100 levels were extracted from the original data files, and the physics rebuilt TAS-faithful from the speedrun community's frame-perfect specs — subpixel movement, jetpack thrust, ladders, and the phaser that digs through the level grid. Sprites stored right-facing only, mirrored by the ASIC. A twin quest on the Atari 7800 is planned. And one rule above all: nothing ships until the original author says yes — the plan is a working prototype first, then a letter to Pedersen asking for his blessing.",
    milestones: [
      { label: "Asset pipeline: 234 tiles + 100 levels reconstructed from DAT files", done: true },
      { label: "CPCtelera toolchain — cart boots in MAME", done: true },
      { label: "Jetman runtime: TAS-faithful subpixel physics, jetpack, phaser", done: true },
      { label: "Full collisions, enemies, complete level loop", done: false },
      { label: "GX4000 deploy: true 12-bit palette on the ASIC", done: false },
      { label: "The author's blessing — then, maybe, the world", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Tandy VIS ---- */
  {
    id: "vis-wolf3d",
    title: "Wolfenstein 3D on the VIS",
    platform: "vis",
    type: "porting",
    status: "ongoing",
    progress: 85,
    summary: "A from-scratch Wolfenstein 3D port running natively as a Win16 app on the VIS: textured raycaster, enemy AI, combat, pickups — and a full 3-channel audio stack (FM music, AdLib SFX, digitized voices via raw DMA on the VIS DAC). 14–18 fps on a 12 MHz 286, and genuinely playable.",
    milestones: [
      { label: "Win16 toolchain + bootable VIS CD forged", done: true },
      { label: "Textured raycaster with doors, sprites and HUD", done: true },
      { label: "Enemy AI, hitscan combat, pickups, ammo economy", done: true },
      { label: "Full audio: IMF music + AdLib SFX + DAC digitized voices", done: true },
      { label: "Full-episode polish and stereo pan", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: ["https://raw.githubusercontent.com/vs-sr-dev/vis-wolf3d/main/wolfvis_demo.gif"],
    repo: "https://github.com/vs-sr-dev/vis-wolf3d",
  },
  {
    id: "vis-synth",
    title: "VIS Synth — an OPL3 instrument",
    platform: "vis",
    type: "homebrew",
    status: "completed",
    progress: 100,
    summary: "The VIS as a musical instrument: an 8-voice OPL3 polyphonic synth played on the hand controller, an SMF MIDI file player, and live MIDI from a real hardware keyboard via a custom MAME ISA-bridge card. All three modes verified — by a musician.",
    milestones: [
      { label: "Hand-controller polyphonic instrument (v0)", done: true },
      { label: "SMF MIDI file player with PIT-µs scheduler (v2)", done: true },
      { label: "Live MIDI from host hardware via custom MAME bridge (v3)", done: true },
    ],
    badges: ["audio-unlocked", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/vis-synth",
  },
  {
    id: "vis-fileviewer",
    title: "VIS File Viewer",
    platform: "vis",
    type: "homebrew",
    status: "completed",
    progress: 100,
    summary: "A media browser the VIS never shipped with: photos, WAV/MIDI audio and Autodesk FLC video played the native Modular Windows way — including a from-scratch FLC player with direct video-RAM writes, because that's how VIS video actually worked (spoiler: it was never AVI).",
    milestones: [
      { label: "Hand-controller file browser as CD shell", done: true },
      { label: "BMP photos + WAV/MIDI via native MCI", done: true },
      { label: "From-scratch FLC video player via DISPDIB DVA", done: true },
    ],
    badges: ["first-boot", "audio-unlocked"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/vis-fileviewer",
  },

  /* ---- Mattel HyperScan ---- */
  {
    id: "hyperscan-homebrew",
    title: "HyperScan: Charting the Uncharted",
    platform: "hyperscan",
    type: "re",
    status: "ongoing",
    progress: 85,
    summary: "The deepest public documentation of the HyperScan: 16+ reproducible bugs in the unmaintained score-elf GCC backend with verified workarounds, PPU register maps, a from-scratch RFID/NFC bit-banging driver — and the first HyperScan audio ever emulated, A/B-matched against a real-hardware capture.",
    milestones: [
      { label: "16+ GCC score-elf compiler bugs root-caused", done: true },
      { label: "PPU register map + I²C controller driver", done: true },
      { label: "From-scratch RFID/NFC card driver via raw GPIO", done: true },
      { label: "First emulated HyperScan audio (MAME SPU work)", done: true },
      { label: "Further pipeline branches", done: false },
    ],
    badges: ["world-first", "disasm", "toolchain", "audio-unlocked", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/hyperscan-homebrew",
    links: [
      { label: "▶ First emulated HyperScan audio", url: "https://www.youtube.com/watch?v=1vh_27eTpfc" },
    ],
  },

  /* ---- Bandai Pippin ---- */
  {
    id: "pippin-homebrew",
    title: "Pippin Online — Networking the @WORLD",
    platform: "pippin",
    type: "re",
    status: "completed",
    progress: 100,
    summary: "The emulated Pippin brought onto the real Internet for the first time: DingusPPC serial/DBDMA fixes (upstreamable), a virtual modem + PPP host stack, Netscape 1.1N loading a live web page — plus a homebrew thin-client browser, and an honest falsification of the image-loading mystery.",
    milestones: [
      { label: "DingusPPC serial/DBDMA fixes (upstreamable)", done: true },
      { label: "Virtual Hayes modem + PPP/NAT host chain", done: true },
      { label: "Netscape loads a live web page from the real Internet", done: true },
      { label: "Thin-client homebrew browser architecture (PPF format)", done: true },
    ],
    badges: ["world-first", "disasm", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/pippin-homebrew",
  },

  /* ---- Neo Geo Pocket Color ---- */
  {
    id: "ngpc-homebrew-notes",
    title: "NGPC ↔ Dreamcast Link Bridge",
    platform: "ngpc",
    type: "re",
    status: "ongoing",
    progress: 80,
    summary: "The NGPC link cable had retail use in 1999 but had never been emulated on either side — until this three-ring bridge connected an NGPC emulator to a Dreamcast emulator, verified on video with both homebrew and retail games. Plus a rescued, fully-documented cc900 toolchain path.",
    milestones: [
      { label: "cc900 toolchain rescued and documented (dead-link-proof)", done: true },
      { label: "First NGPC↔DC link-cable bridge in emulation", done: true },
      { label: "Verified with retail games on video", done: true },
      { label: "Further pipeline branches", done: false },
    ],
    badges: ["world-first", "disasm", "toolchain", "first-boot"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/ngpc-homebrew-notes",
    links: [
      { label: "▶ First working bridge (homebrew)", url: "https://www.youtube.com/watch?v=x2IV3T3Z0oM" },
      { label: "▶ Retail-software bridge test", url: "https://www.youtube.com/watch?v=mmxnnkZzu-s" },
    ],
  },

  /* ---- Atari Jaguar ---- */
  {
    id: "jag-ff4",
    title: "Final Fantasy IV — Atari Jaguar",
    platform: "jaguar",
    type: "porting",
    status: "ongoing",
    progress: 15,
    summary: "The maddest route in the codex: FF4 brought to the Jaguar not by rewriting it, but by transpiling the entire SNES disassembly — a custom-built 65c816→68k transpiler (all six modules green, 4.78 MB of generated assembly), a byte-perfect SNES build as the oracle, and a software SNES-PPU bridge feeding the Jaguar. The AKAO sound engine has been rebuilt to SNES fidelity: the Prelude and Edward's harp validated by ear as 'practically identical'. Current front line: the opening Red Wings flight, where Mode 7 meets a console that never had one. The tiny progress bar is honest — this is the tears-and-blood pipeline, fought one hard-won session at a time.",
    milestones: [
      { label: "Custom 65c816→68k transpiler — six modules, 4.78 MB of asm", done: true },
      { label: "Boots on Jaguar: trampoline dispatch, title screen passes", done: true },
      { label: "Full sync pipeline: NMI dispatch, pad input arriving", done: true },
      { label: "AKAO audio at SNES fidelity — validated by a musician's ear", done: true },
      { label: "Red Wings opening: Mode 7 + sprites (4 root causes fixed, validating)", done: false },
      { label: "Field, menus, battles… the mountain", done: false },
    ],
    badges: ["toolchain", "disasm", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  {
    id: "jag-lba1",
    title: "Little Big Adventure — Atari Jaguar",
    platform: "jaguar",
    type: "porting",
    status: "ongoing",
    progress: 20,
    summary: "The tenth life of LBA in this codex, and among the hardest-won: LBA1 on a 6 MB Jaguar cartridge with bank switching, rendered by a polygon rasterizer written instruction by instruction in GPU TOM assembly — four-edge clipping, Gouraud shading, spheres — until Twinsen stands correctly shaded in the Citadel and walks through multi-room scrolling at 60 fps. The crown jewel: the Jaguar's 480i interlaced mode, which no retail game ever shipped, switched on to chase 1:1 parity with the PC DOS original at 640×480. Local-only until the rights holders say yes.",
    milestones: [
      { label: "Citadel scene rendered; 134-scene cart; multi-room scroll at 60 fps", done: true },
      { label: "GPU TOM rasterizer from scratch: clipping, fill, Gouraud, spheres", done: true },
      { label: "Twinsen walkable, sprite-based body — bus contention defeated", done: true },
      { label: "640×480i interlace — a mode no retail Jaguar game ever used", done: true },
      { label: "Animations, collisions, script engine from the community fork", done: false },
      { label: "The mountain, again", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Panasonic 3DO ---- */
  {
    id: "3do-omf2097",
    title: "One Must Fall: 2097 on the 3DO",
    platform: "3do",
    type: "porting",
    status: "ongoing",
    progress: 40,
    summary: "Can a 3DO run OMF's CEL engine at a playable rate? Yes: a complete 1-v-1 match vs the AI — pilot select, real movesets, throws, knockback, per-arena music, KO — built on OpenOMF and squeezed under the 32-colour PLUT cap. Version 0.1, 'playable 1v1'.",
    milestones: [
      { label: "Playable 1v1 vs AI with full scene flow", done: true },
      { label: "Data-driven movesets, throws, damage, SFX + music", done: true },
      { label: "All 10 HARs wired as fighters (2/10 so far)", done: false },
      { label: "Rounds, stun bar, arena hazards, victory poses", done: false },
    ],
    badges: ["first-boot", "toolchain"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/3do-omf2097",
  },

  /* ---- Sega 32X ---- */
  {
    id: "32x-lba1",
    title: "Little Big Adventure — Sega 32X",
    platform: "32x",
    type: "porting",
    status: "ongoing",
    progress: 60,
    summary: "Filed as '99% infeasible' at kickoff — 19 sessions later the real LBA1 engine runs from pure LIFE/TRACK bytecode on the mushroom. Along the way: isometric scene split across both SH-2s, a Gouraud-shaded 3D Twinsen, and an audio odyssey that ended with the 68000 driving the Genesis YM2612 directly — five empirical OPL2→FM translation rules squeezing all 33 music tracks into 55 KB instead of 10 MB of PCM. All four CPUs employed. 1.48 MB of the 4 MB cart used.",
    milestones: [
      { label: "Iso brick scene + interactive camera on dual SH-2", done: true },
      { label: "Gouraud 3D Twinsen: animations, behaviors, collisions", done: true },
      { label: "FM audio: 68000-driven YM2612, 33 tracks in 55 KB", done: true },
      { label: "Intro slides, typewriter dialogs, inventory, pickups", done: true },
      { label: "Engine pivot: real LIFE/TRACK bytecode, DoAnim/DoDir 1:1", done: true },
      { label: "Combat damage, zone dialogs, full first-scene closure", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },
  {
    id: "32x-lba2",
    title: "Little Big Adventure 2 — Sega 32X",
    platform: "32x",
    type: "porting",
    status: "ongoing",
    progress: 35,
    summary: "The sibling wager: LBA2's outdoor 3D is mostly static and flat, so how far can the LBA1/32X pipeline stretch? Interiors reuse the iso brick renderer; outdoors get a compact scene graph with frustum culling split across both SH-2s. The cube-0 opening runs from real LIFE bytecode — Twinsen and Zoe scripted, dialog on screen, hero controllable afterwards. Current front line: replacing the placeholder hero locomotion model with a faithful PERSO port.",
    milestones: [
      { label: "Interior iso scenes via the LBA1/32X pipeline", done: true },
      { label: "Outdoor static 3D, frustum cull on dual SH-2", done: true },
      { label: "Engine bring-up: LIFE bytecode + dialogs in cube 0", done: true },
      { label: "Faithful hero animation / orientation (PERSO port)", done: false },
      { label: "FM audio reuse, island selection under the 4 MB cart", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Sony PlayStation ---- */
  {
    id: "ps1-vampire-re",
    title: "Vampire: Kyūketsuki Densetsu — Translation Quest",
    platform: "ps1",
    type: "re",
    status: "ongoing",
    progress: 15,
    summary: "A quest born of friendship: a private English translation of Artdink's PS1 retelling of Dracula — Jonathan the lawyer, his fiancée Rose, Count Varaur, London — as a gift for a friend who loves vampires. Session two struck gold: the entire story turned out to be plaintext Shift-JIS, and all ~12,400 narrative characters are dumped and catalogued. The scene-script bytecode has been structurally cracked. Still embryonic, and carried out with its own etiquette: another fan translator is at work on the same game, so the plan is to reach out before going deep — and this stays personal, never a public release.",
    milestones: [
      { label: "Disc structure and containers parsed, assets classified", done: true },
      { label: "All narrative text dumped: ~12,400 chars, 607 unique kanji", done: true },
      { label: "Scene-script bytecode structurally cracked", done: true },
      { label: "Text renderer RE + reinsertion pipeline", done: false },
      { label: "The translation itself — a gift, not a release", done: false },
    ],
    badges: ["disasm"],
    screenshots: [],
    repo: null,
  },

  /* ---- Nintendo 64 ---- */
  {
    id: "n64-lba2",
    title: "Little Big Adventure 2 — Nintendo 64",
    platform: "n64",
    type: "porting",
    status: "ongoing",
    progress: 65,
    summary: "The Wii U port's big-endian twin: LBA2 on libdragon with no leaked SDK, the software renderer presented through the RDP as a palette blit, and a MIPS unaligned-access emulator written into the exception handler to tame the engine's packed data. The game runs — 58 VPS in Twinsen's house, exteriors working, 12-voice SFX on the RSP mixer and Opus music streaming from a 45 MB ROM.",
    milestones: [
      { label: "Docker toolchain — full engine compiles and boots on Ares", done: true },
      { label: "Game runs: first scene, dialogs, scripts, input complete", done: true },
      { label: "Unaligned-access emulator in the MIPS exception handler", done: true },
      { label: "Audio: 12-voice RSP SFX + streamed Opus music, in-game", done: true },
      { label: "RSP crash on scene change (double-buffered TLUT fix to verify)", done: false },
      { label: "Voice-over repack under 64 MB, SRAM saves, FMV, polish", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Sega Dreamcast ---- */
  {
    id: "dc-lba2",
    title: "Little Big Adventure 2 — Dreamcast",
    platform: "dreamcast",
    type: "porting",
    status: "bossfight",
    progress: 75,
    summary: "The original 1997 Adeline engine compiled for the Dreamcast via KallistiOS: first island playable to completion on Flycast with FMV, music, voices, VMU saves. The boss fight: on real hardware boot stalls after the EA logo — first UART capture has pinned a render-side crash, diagnosis underway.",
    milestones: [
      { label: "Engine boots: intro FMV, menu, gameplay on Flycast", done: true },
      { label: "First island completable; second island loads", done: true },
      { label: "Audio streams + VMU save/load", done: true },
      { label: "BOSS: real-Dreamcast boot blocker (UART diagnosis)", done: false },
      { label: "Full playthrough validation", done: false },
    ],
    badges: ["first-boot", "toolchain"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/dc-lba2",
  },

  {
    id: "dc-ff8",
    title: "Final Fantasy VIII — Dreamcast",
    platform: "dreamcast",
    type: "porting",
    status: "ongoing",
    progress: 40,
    summary: "The game the Dreamcast never got, rebuilt the honest way: a C++ reimplementation on KallistiOS that executes FF8's own data — the field scenes run their authentic script bytecode (the Balamb infirmary plays out its real 1,960-op program), stats come from kernel.bin, and the physical damage formula is transcribed from byte-matching decompiled code. Triple Triad is fully playable and 'unsettlingly identical'; the whole party walks in 3D at 60 fps inside the real painted backdrops with depth occlusion; battle monsters animate on real 3D stages with authentic UI art. Includes an original RE contribution: the field bone-rotation decode, verified against the PS1 assembly nobody had decompiled. Bring-your-own-assets throughout. And parked in a drawer: Chocobo World running its original ARM ROM on the VMU via a home-made PocketStation emulator.",
    milestones: [
      { label: "Triple Triad 1:1 — all rules, authentic art, SFX and BGM", done: true },
      { label: "Field: party in 3D at 60 fps inside real backdrops, depth-occluded", done: true },
      { label: "Field VM: authentic JSM bytecode executed (infirmary scene live)", done: true },
      { label: "Battle slice: real formulas, monster stats, stages, authentic UI", done: true },
      { label: "FMV pipeline proven (RoQ streaming with audio)", done: true },
      { label: "Magic/GF effect compositor — the frontier nobody has decompiled", done: false },
      { label: "Enemy-AI bytecode interpreter, main menu, VMU saves", done: false },
    ],
    badges: ["toolchain", "first-boot", "disasm", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  {
    id: "dc-mi3",
    title: "The Curse of Monkey Island — Dreamcast",
    platform: "dreamcast",
    type: "porting",
    status: "bossfight",
    progress: 70,
    summary: "ScummVM bug #6008: SCUMM v8 games have never run on the Dreamcast — a wall standing for some twenty years. This quest broke it. Built on the alternate KallistiOS backend, the memory war was won lever by lever: 3.5 MB of GUI TrueType fonts evicted, a 600 KB buffer upstream allocates by mistake removed, costumes flushed before cutscenes — while a concurrent CD-I/O race and a 32 KB thread-stack overflow (masquerading as a dozen different corruptions) were root-caused and fixed. Result: The Curse of Monkey Island boots, plays its intro FMV with sound, and renders real gameplay — Guybrush and Wally in the ship hold — at 52 fps on a stock 16 MB Dreamcast, the deepest CMI has ever run on the console. The boss: a main-thread hang right before the first spoken line.",
    milestones: [
      { label: "dcalt/KOS ScummVM built from source with SCUMM v8 enabled", done: true },
      { label: "Boots in 16 MB: theme-font diet, intro, difficulty select, audio", done: true },
      { label: "Intro FMV with sound in sync + chapter card with music", done: true },
      { label: "CD-I/O race and thread-stack corruption root-caused and fixed", done: true },
      { label: "Real gameplay rendered at 52 fps — past the historic wall", done: true },
      { label: "BOSS: main-thread hang before the first dialogue line", done: false },
      { label: "Full playability pass, upstreamable fixes, real hardware", done: false },
    ],
    badges: ["toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Nintendo Wii U ---- */
  {
    id: "wiiu-lba2",
    title: "Little Big Adventure 2 — Wii U",
    platform: "wiiu",
    type: "porting",
    status: "completed",
    progress: 100,
    summary: "V1.0: the original 1997 Adeline source running natively on the Wii U — completed start to finish on real hardware, full story, all cutscenes and FMVs, 50–80 fps, native AX audio, GamePad touch panel for behaviours and spells, saves with on-screen keyboard. ~99.9% parity with the original.",
    milestones: [
      { label: "Big-endian PowerPC port of the DOS/Win95 engine", done: true },
      { label: "FMV streaming, AX audio, saves, full GamePad + touch", done: true },
      { label: "Complete playthrough validated on real hardware", done: true },
      { label: "Post-release polish (controls tuning, touch labels)", done: false },
    ],
    badges: ["released", "real-hardware", "first-boot", "toolchain"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/wiiu-lba2",
  },

  /* ---- Amiga CD32 ---- */
  {
    id: "cd32-lba1",
    title: "Little Big Adventure — Amiga CD32",
    platform: "cd32",
    type: "porting",
    status: "ongoing",
    progress: 35,
    summary: "The 1994 Adeline engine squeezed into 2 MB of chip RAM on a big-endian 68020: boots from CD, Akiko C2P rendering, and a perfect main menu at native 320×240 — where a key discovery (the engine's projection is hard-coded) means the native view IS the original 1994 view. Current front line: a crash in the object renderer, first scene almost in sight.",
    milestones: [
      { label: "M0: Akiko C2P HQR viewer boots from ISO", done: true },
      { label: "M1: full engine compiles, boots, Adeline logo on screen", done: true },
      { label: "M2: native 320×240 render — menu perfect, 2 MB RAM wall beaten", done: true },
      { label: "First in-game scene (object-renderer crash under diagnosis)", done: false },
      { label: "M4: Paula SFX, CDDA music, NVRAM saves", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Nintendo DS ---- */
  {
    id: "ds-lba1",
    title: "Little Big Adventure — Nintendo DS",
    platform: "ds",
    type: "porting",
    status: "ongoing",
    progress: 70,
    summary: "LBA1 playable on the DS at a locked 50 fps: the real engine ITCM/ARM-optimized down to 6.5 ms per 3D actor, persistent saves on SD, SFX and voice acting through the hardware audio channels — and a custom touch HUD on the second screen with live health, money and one-tap behaviour switching. Fits a stock 4 MB DS with 1.5 MB to spare.",
    milestones: [
      { label: "Boots to gameplay: logos, menu, intro, first scene", done: true },
      { label: "50 fps gameplay after ITCM/DTCM optimization campaign", done: true },
      { label: "Persistent savegames on SD card", done: true },
      { label: "SFX + dialog voices via ARM7 hardware channels", done: true },
      { label: "Touch HUD on second screen with live stats", done: true },
      { label: "Music, remaining islands' voices, full-game validation", done: false },
    ],
    badges: ["real-hardware", "toolchain", "first-boot", "audio-unlocked"],
    screenshots: [],
    repo: null,
  },

  /* ---- Game Boy Advance ---- */
  {
    id: "gba-lba1-poc",
    title: "Little Big Adventure — GBA (Proof of Concept)",
    platform: "gba",
    type: "porting",
    status: "ongoing",
    progress: 30,
    summary: "Not a demake: the genuine LBA1 engine — LIFE/TRACK script interpreters, brick collisions, 3D actor animation — running the opening asylum cell on a 16.78 MHz ARM7TDMI with 256 KB of RAM. A measured 4.7× optimization journey (ROM waitstates, IWRAM/ARM hot code, radix painter sort) took it from 3.5 to 16.5 fps, dialog with the nurse included.",
    milestones: [
      { label: "Real engine slice on ARM: scene, scripts, collisions", done: true },
      { label: "Twinsen fully animated (180 verts, Gouraud rasterizer)", done: true },
      { label: "Dialog system with authentic TEXT.HQR data", done: true },
      { label: "3.5 → 16.5 fps measured optimization campaign", done: true },
      { label: "Scenes beyond cube 0, audio", done: false },
    ],
    badges: ["first-boot", "toolchain"],
    screenshots: [
      "assets/gba-lba/1-bricks.png",
      "assets/gba-lba/2-twinsen.png",
      "assets/gba-lba/3-engine.png",
      "assets/gba-lba/4-nurse.png",
    ],
    repo: null,
  },

  /* ---- Super Nintendo ---- */
  {
    id: "snes-rudra-re",
    title: "Rudra no Hihō — Text & Sound RE",
    platform: "snes",
    type: "re",
    status: "ongoing",
    progress: 45,
    summary: "Decoding the Japanese text system of Square's Treasure of the Rudras: custom 2-byte kanji encoding, DTE dictionaries, inline furigana — ~286 of ~730 kanji codes identified. A second track cracked the AKAO sound engine, ending in a fully static SPC extractor that rips every song from ROM tables alone, no emulator needed.",
    milestones: [
      { label: "Kana layout, control codes, DTE dictionary decoded", done: true },
      { label: "AKAO sound engine + emulator-free static SPC ripper", done: true },
      { label: "Kanji table: 286 / ~730 codes identified", done: false },
    ],
    badges: ["disasm", "audio-unlocked"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/snes-rudranohihou-re",
  },

  {
    id: "snes-lba1-poc",
    title: "Little Big Adventure — SNES + SuperFX (PoC)",
    platform: "snes",
    type: "porting",
    status: "ongoing",
    progress: 55,
    summary: "The real LBA1 engine on a 65816, with a SuperFX GSU composing the isometric scene straight into SNES bitplane format — driven by hand-written GSU assembly built with a from-scratch Python mini-assembler. The prison's upper floor is alive: 23 actors, LIFE/TRACK scripts and zones running, the hover platform flying to the hero on cue, pixel-exact sprite occlusion behind the cell fence.",
    milestones: [
      { label: "Feasibility study + M0: prison scene in Mode 3, budgets validated", done: true },
      { label: "M1: SuperFX compositor pixel-perfect vs reference + camera pan", done: true },
      { label: "M2: engine alive in C — Twinsen walks and collides (~30 fps hero-only)", done: true },
      { label: "M3: full scene — 23 actors, scripts, zones, GSU sprite-clip occlusion", done: true },
      { label: "Dialog textbox + performance pass (11–25 fps with NPCs today)", done: false },
      { label: "M4: true flat-3D hero rendered by the GSU · M5: SPC700 audio", done: false },
    ],
    badges: ["toolchain", "first-boot"],
    screenshots: [],
    repo: null,
  },

  /* ---- Smaky ---- */
  {
    id: "smaky-ff1",
    title: "Final Fantasy — Smaky (The Anachronistic Remake)",
    platform: "smaky",
    type: "porting",
    status: "accepted",
    progress: 10,
    summary: "The codex's most gloriously improbable quest: what if Square had owned a Smaky instead of a Famicom? FF1 remade for the Swiss school computer — hardware released three years before the game, yet mightier than a NES: a 68000, a full megabyte of RAM, a real keyboard, and 640×400 of green phosphor. No bank switching, no text compression — the challenge is making tiles readable in pure monochrome dithering. The Smaky 100's innards were never publicly documented, so the port targets a 'fantasy console' faithful to every authentic spec. Toolchain proven, the FF1 font already glows green. An informal race is on against the ColecoVision and 7800 siblings for the first shippable demo — and this machine from a stranger timeline may yet play a larger role in tales to come.",
    milestones: [
      { label: "Spec sprint: authentic Smaky 100 specs triangulated from Swiss sources", done: true },
      { label: "Toolchain + green-phosphor harness proven (68000 hello)", done: true },
      { label: "FF1 font pipeline rendering on the mono display", done: true },
      { label: "Party generation, 80×60 overworld, dithered tile art", done: false },
      { label: "First shippable demo — the FF1 sibling race", done: false },
    ],
    badges: ["toolchain"],
    screenshots: [],
    repo: null,
  },

  /* ---- The PC ---- */
  {
    id: "pc-silver-re",
    title: "Silver (1999) — Engine Archaeology, toward Co-op",
    platform: "pc",
    type: "re",
    status: "ongoing",
    progress: 55,
    summary: "A full dig into Spiral House's 1999 action-RPG: every scene format decoded (308 backgrounds with pixel-perfect depth occlusion), the rolling-XOR dialog cipher cracked (2,828 lines recovered), character models rebuilt with skeletons and animations — down to discovering the on-disk quaternions are stored (z,x,y,w) — and the walkmesh of all 287 scenes parsed. The Dreamcast build was disassembled too, to settle an input-system mystery. End goal: a code-patch mod bringing co-op play to the 3-member party. Documentation and methodology only — no assets, no code dumps; the game is still on sale.",
    milestones: [
      { label: "All 308 backgrounds + depth/occlusion decoded pixel-perfect", done: true },
      { label: "Dialog cipher cracked — 2,828 lines recovered", done: true },
      { label: "Models, textures, UVs, skeletons, animations fully decoded", done: true },
      { label: "Walkmesh / pathfinding graph parsed for all 287 scenes", done: true },
      { label: "Input system mapped — incl. Dreamcast SH-4 disassembly cross-check", done: true },
      { label: "Co-op mode mod via code patches", done: false },
    ],
    badges: ["disasm", "toolchain"],
    screenshots: [],
    repo: null,
  },

  {
    id: "pc-tle-re",
    title: "The Last Express (1997) — Clockwork of the Orient Express",
    platform: "pc",
    type: "re",
    status: "ongoing",
    progress: 60,
    summary: "Digging into Jordan Mechner's real-time masterpiece through its modern re-release — a cocos2d-x shell around the nearly intact 1997 game. All major formats decoded: backgrounds, audio, the subtitle system with its custom bitmap font (perfect text in five languages), actor-sprite RLE, and the NIS cutscene containers — whose engine turned out to be byte-identical to the 1997 original. The character-AI virtual machine was mapped in the exe, down to reversing the exact trigger of the infamous 'August finds the corpse' game over, cross-confirmed against ScummVM at three matching call sites. Documentation and tooling only — the game is still on sale.",
    milestones: [
      { label: "Backgrounds, audio, subtitles + custom font fully decoded", done: true },
      { label: "SEQ actor sprites decoded (all RLE packing variants)", done: true },
      { label: "NIS cutscene containers + sprite decode solved", done: true },
      { label: "Entity VM mapped; the 1009 game-over trigger reversed", done: true },
      { label: "Fade sprites, NIS playback timing, train scene graph", done: false },
    ],
    badges: ["disasm", "toolchain"],
    screenshots: [],
    repo: null,
  },

  {
    id: "pc-risinglands-wrap",
    title: "Rising Lands — Zero-Friction Compatibility Layer",
    platform: "pc",
    type: "tooling",
    status: "ongoing",
    progress: 85,
    summary: "The codex's only time-reversed port: instead of carrying a game back to old silicon, this carries Microïds' 1997 RTS forward to Windows 11 — no drivers, no mounted ISO, no physical CD. A drop-in winmm.dll proxy, reverse-engineered from the game's own MCI command strings, replays the CD soundtrack from OGG files and fakes the disc's presence; DDrawCompat cures the palette; a tiny launcher pins the Pentium-era timing loop to one core. The deep cut: a savage in-game crash root-caused with a vectored-exception logger and trampoline hooks down to a mission file hard-wired to the CD path — fixed with a redirect-on-failure file hook that cures the whole class. Mission 1 confirmed fully playable, one-click installer built. Bring your own game.",
    milestones: [
      { label: "winmm proxy: MCI→OGG music + CD-presence faking", done: true },
      { label: "Video and timing: DDrawCompat, single-core pinning, DPI manifest", done: true },
      { label: "In-game crash root-caused (CD-hardwired path) and fixed", done: true },
      { label: "v1.0 one-click installer; mission 1 fully playable", done: true },
      { label: "Full 25-mission campaign validation", done: false },
    ],
    badges: ["toolchain", "disasm"],
    screenshots: [],
    repo: null,
  },

  {
    id: "pc-replay-vault",
    title: "The Replay Vault — Childhood Titles Revived",
    platform: "pc",
    type: "tooling",
    status: "ongoing",
    progress: 80,
    summary: "A gentler kind of quest: not forcing games onto impossible hardware, but bringing the titles of an Italian childhood back to life on modern machines — and actually replaying them, start to finish. Each one its own puzzle: Tip Top (Director 5 + QuickTime) solved through Mac OS 9 emulation after ScummVM fell short; RAI's Stellaris (16-bit ToolBook + Indeo video) coaxed onto Windows 11 through otvdm and codec archaeology; Coktel Vision's A.J.'s World running under ScummVM; QBasic Gorillas reborn in DOSBox-X — complete with a custom amber-monitor GLSL shader for full 1991 flavour; and AEnigmatica, a 1998 puzzle CD that turned out to be a Java 1.1 app with hardcoded JDK quirks, still resisting. Bonus escapade: Tip Top booted natively on an emulated Bandai Pippin, AppleJack pad and all.",
    milestones: [
      { label: "Tip Top — 100% playable via SheepShaver / Mac OS 9", done: true },
      { label: "Stellaris: Sfida a StarCity — on Win11 via otvdm + Indeo codecs", done: true },
      { label: "A.J.'s World of Discovery — running under ScummVM", done: true },
      { label: "Gorillas + Battle Bugs — DOSBox-X, amber-phosphor shader included", done: true },
      { label: "AEnigmatica — the Java 1.1 sphinx still guards her riddle", done: false },
      { label: "Tip Top on the Pippin — boots natively; cutscene boss remains", done: false },
    ],
    badges: ["toolchain"],
    screenshots: [],
    repo: null,
  },

  /* ---- The Chip Forge ---- */
  {
    id: "chiproll",
    title: "ChipRoll — Piano Roll for Chip Music",
    platform: "forge",
    type: "tooling",
    status: "ongoing",
    progress: 85,
    summary: "A browser piano roll that lets musicians write for the NES, Atari TIA and POKEY the way they'd write anything else: DAW-style grid, MIDI import with auto BPM stretch, live MIDI recording, chip-accurate intonation feedback, and song-aware exports straight to FamiTracker text and ca65 assembly.",
    milestones: [
      { label: "NES + TIA + POKEY engines with pattern/song sequencing", done: true },
      { label: "MIDI import pipeline + Web MIDI live recording", done: true },
      { label: "Song-aware exports: FamiTracker, ca65, chip-native", done: true },
      { label: "POKEY v2 (16-bit joins, alt clocks), MusicXML import", done: false },
    ],
    badges: ["released", "audio-unlocked"],
    screenshots: [],
    repo: "https://github.com/vs-sr-dev/chiproll",
  },
];
